/**
 * Shared chat-turn envelope schema.
 *
 * Moved out of `experience-ai-chat.service.ts` so the CLI adapters
 * (Codex, Claude Code) can pass a JSON-schema serialization to the
 * CLI's `--output-schema` / `--json-schema` flag without re-importing
 * the service (which would be a circular dependency).
 *
 * The Zod schemas remain the runtime source of truth — the CLI's
 * schema enforcement is a hint, not a guarantee, so the chat service
 * re-validates the parsed envelope via these schemas before applying
 * the mutation.
 *
 * `buildChatMutationEnvelopeJsonSchema()` is hand-coded against the
 * Zod shape rather than generated by `zod-to-json-schema` — the
 * envelope is small and stable, the dep would be one more thing to
 * keep in lockstep, and CLIs expect plain JSON Schema (not Zod's
 * internal representation).
 */

import { z } from "zod"

export const ChatMutationsSchema = z
  .object({
    title: z.string().optional(),
    metaDescription: z.string().nullable().optional(),
    blocks: z.array(z.unknown()).optional(),
    ogImageUrl: z.string().url().nullable().optional(),
  })
  .strict()

export const ChatMutationEnvelopeSchema = z
  .object({
    mutations: ChatMutationsSchema,
    localesAffected: z.array(z.string()).optional(),
    reason: z.string().optional(),
  })
  .strict()

export type ChatMutationEnvelope = z.infer<typeof ChatMutationEnvelopeSchema>

/**
 * JSON-schema serialization of `ChatMutationEnvelopeSchema` suitable
 * for `codex exec --output-schema` and `claude --json-schema`.
 *
 * `blocks` is intentionally loose (`{type: "array"}` with no `items`)
 * because the canonical block union lives in `src/domain/blocks.ts`
 * and a full JSON-Schema reflection of the discriminated union is
 * tied to that file. The Zod re-validation step in the chat service
 * narrows it to the strict shape.
 */
export function buildChatMutationEnvelopeJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    additionalProperties: false,
    properties: {
      mutations: {
        type: "object",
        additionalProperties: false,
        properties: {
          title: { type: "string" },
          metaDescription: { type: ["string", "null"] },
          blocks: { type: "array" },
          ogImageUrl: {
            anyOf: [{ type: "string", format: "uri" }, { type: "null" }],
          },
        },
      },
      localesAffected: {
        type: "array",
        items: { type: "string" },
      },
      reason: { type: "string" },
    },
    required: ["mutations"],
  }
}
