// Pothos types for VideoScene and VideoSceneLocale.
//
// Scene data is language-agnostic (timecodes + chapter titles) and public-
// shape — Core-sourced multimodal pipeline output, not editor-owned. The
// per-locale row (VideoSceneLocale) carries description + metadata + the
// embedding vector; the `embedding` field is INTENTIONALLY OMITTED from
// the Pothos field list so it never leaves the backend. The schema test
// in `schema.test.ts` asserts the "no embed|vector|similarit" contract
// across the full SDL.

import { builder } from "@/graphql/builder"

/** @classification public-shape */
builder.prismaObject("VideoScene", {
  description:
    "A timecoded scene segment of a VideoEdition. Scenes are language-agnostic; per-locale descriptions live on VideoSceneLocale.",
  fields: (t) => ({
    id: t.exposeID("id"),
    videoEditionId: t.exposeID("videoEditionId"),
    videoId: t.exposeID("videoId"),
    sceneIndex: t.exposeInt("sceneIndex"),
    startSeconds: t.exposeFloat("startSeconds"),
    endSeconds: t.exposeFloat("endSeconds", { nullable: true }),
    chapterTitle: t.exposeString("chapterTitle", { nullable: true }),
    createdAt: t.string({ resolve: (row) => row.createdAt.toISOString() }),
    updatedAt: t.string({ resolve: (row) => row.updatedAt.toISOString() }),
    locales: t.relation("locales", {
      description: "Per-locale scene description + metadata.",
    }),
  }),
})

/** @classification public-shape */
builder.prismaObject("VideoSceneLocale", {
  description:
    "A per-locale scene description generated by apps/manager's multimodal pipeline. The underlying embedding vector is never exposed via GraphQL.",
  fields: (t) => ({
    id: t.exposeID("id"),
    videoSceneId: t.exposeID("videoSceneId"),
    locale: t.exposeString("locale"),
    description: t.exposeString("description"),
    themes: t.exposeStringList("themes"),
    bibleVerses: t.exposeStringList("bibleVerses"),
    demographics: t.exposeStringList("demographics"),
    spiritualContext: t.exposeStringList("spiritualContext"),
    // NOTE: `embedding` deliberately omitted. Enforced by schema.test.ts.
    // `sourceText`, `model`, and `dimensions` are backend-only operational
    // metadata and intentionally not exposed.
    createdAt: t.string({ resolve: (row) => row.createdAt.toISOString() }),
    updatedAt: t.string({ resolve: (row) => row.updatedAt.toISOString() }),
  }),
})
