// Plain JS (like the other guard suites): the RN tsconfig has no Node types,
// and this guard needs fs, path, and child_process to run the generator.
/* eslint-disable @typescript-eslint/no-require-imports */
/* global afterAll, describe, expect, it, require */
const childProcess = require("child_process")
const fs = require("fs")
const os = require("os")
const path = require("path")

// Guard: the Admin language tables (KTD9) must match web's map, web's curated
// table, web's catalog list, and mobile's override file.
const MOBILE_DIR = path.join(__dirname, "..", "..", "..")
const SCRIPT = path.join(
  MOBILE_DIR,
  "scripts",
  "i18n",
  "generate-admin-languages.mjs",
)
const WEB_MESSAGES_DIR = path.join(MOBILE_DIR, "..", "web", "messages")
const GENERATED = "adminLanguages.generated.ts"

const tempDirs = []

function tempDir() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "admin-languages-"))
  tempDirs.push(dir)
  return dir
}

function runGenerator(args) {
  return childProcess.spawnSync(process.execPath, [SCRIPT, ...args], {
    encoding: "utf8",
  })
}

function mapSource(entries, headerCount = entries.length) {
  const lines = entries.map(([slug, tag]) => `    "${slug}": "${tag}",`)
  return [
    "// AUTOGENERATED from admin Language.bcp47 on 2026-09-11",
    `// ${headerCount} entries (0 admin rows skipped).`,
    "export const LANGUAGE_BCP47_MAP: Readonly<Record<string, string>> =",
    "  Object.freeze({",
    ...lines,
    "  })",
    "",
  ].join("\n")
}

function localeSource(curated) {
  const lines = Object.entries(curated).map(
    ([tag, slug]) => `  "${tag}": "${slug}",`,
  )
  return [
    "const PUBLIC_WATCH_AUDIO_LANGUAGE_SLUG_BY_UI_LOCALE: Readonly<",
    "  Record<string, string>",
    "> = Object.freeze({",
    ...lines,
    "})",
    "",
  ].join("\n")
}

const BASE_MAP = [
  ["csango", "hu"],
  ["english", "en"],
  ["hausa", "ha"],
  ["hungarian", "hu"],
  ["norwegian-bokmal", "no"],
  ["spanish-castilian", "es-ES"],
  ["spanish-latin-american", "es"],
]

const BASE_OVERRIDES = {
  text: {},
  audio: {},
  forYou: {},
}

/** A web dir, an override file, and an out file, all in a temp dir. */
function fixture({
  catalogs = ["en", "es", "hu", "ab"],
  map = BASE_MAP,
  curated = { en: "english" },
  overrides = BASE_OVERRIDES,
} = {}) {
  const root = tempDir()
  const webDir = path.join(root, "web")
  fs.mkdirSync(path.join(webDir, "messages"), { recursive: true })
  fs.mkdirSync(path.join(webDir, "src", "lib"), { recursive: true })
  for (const tag of catalogs) {
    fs.writeFileSync(path.join(webDir, "messages", `${tag}.json`), "{}\n")
  }
  const mapFile = path.join(webDir, "src", "lib", "language-bcp47-map.ts")
  fs.writeFileSync(mapFile, mapSource(map))
  fs.writeFileSync(
    path.join(webDir, "src", "lib", "locale.ts"),
    localeSource(curated),
  )
  const overridesFile = path.join(root, "overrides.json")
  fs.writeFileSync(overridesFile, JSON.stringify(overrides, null, 2))
  const outFile = path.join(root, GENERATED)
  const args = [
    `--web-dir=${webDir}`,
    `--overrides=${overridesFile}`,
    `--out=${outFile}`,
  ]
  return { args, mapFile, outFile }
}

/** The tables the generator computes, from its `--json` mode. */
function tables(args) {
  const result = runGenerator([...args, "--json"])
  expect(result.stderr).toBe("")
  expect(result.status).toBe(0)
  return JSON.parse(result.stdout)
}

function entry(slug, reason = "Fixture.") {
  return { slug, reason }
}

function sourceFiles(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((item) => {
    if (item.name === "node_modules") return []
    const full = path.join(dir, item.name)
    if (item.isDirectory()) return sourceFiles(full)
    return /\.(ts|tsx|js)$/.test(item.name) ? [full] : []
  })
}

// A relative path into apps/web passes through a `../web/` segment.
const WEB_IMPORT =
  /(?:from\s+|require\(\s*|import\(\s*)["'][^"']*(?:apps\/web\b|@forge\/web\b|\.\.\/web\/)/

afterAll(() => {
  for (const dir of tempDirs) fs.rmSync(dir, { recursive: true, force: true })
})

describe("Admin language tables", () => {
  it("--check passes on the committed table", () => {
    const result = runGenerator(["--check"])
    expect(result.stderr).toBe("")
    expect(result.status).toBe(0)
  })

  it("has one entry for each web catalog", () => {
    const catalogs = fs
      .readdirSync(WEB_MESSAGES_DIR)
      .filter((name) => name.endsWith(".json"))
      .map((name) => name.slice(0, -".json".length))
      .sort()
    const { forms } = tables([])
    expect(Object.keys(forms).sort()).toEqual(catalogs)
  })

  it("--check fails when the web map adds a slug for an unmapped catalog (negative control)", () => {
    const { args, mapFile } = fixture()
    expect(runGenerator(args).status).toBe(0)
    expect(runGenerator([...args, "--check"]).status).toBe(0)
    expect(tables(args).forms.ab.textSlug).toBe("english")

    fs.writeFileSync(mapFile, mapSource([...BASE_MAP, ["abkhaz", "ab"]]))
    const result = runGenerator([...args, "--check"])
    expect(result.status).toBe(1)
    expect(result.stderr).toContain(GENERATED)
    expect(tables(args).forms.ab.textSlug).toBe("abkhaz")
  })

  it("--check fails when the generated file is edited by hand", () => {
    const { args, outFile } = fixture()
    expect(runGenerator(args).status).toBe(0)
    fs.appendFileSync(outFile, "// hand edit\n")
    const result = runGenerator([...args, "--check"])
    expect(result.status).toBe(1)
    expect(result.stderr).toContain(GENERATED)
  })

  it("takes the first slug in map order when no override names one", () => {
    const { forms, audio } = tables(fixture().args)
    expect(forms.hu).toEqual({
      catalogTag: "hu",
      forYouLocale: "hu",
      textSlug: "csango",
      rawTag: "hu",
    })
    expect(audio.hu).toBe("csango")
  })

  it("lets a text override beat the first slug with the same tag", () => {
    const { args } = fixture({
      overrides: {
        ...BASE_OVERRIDES,
        text: { hu: entry("hungarian") },
      },
    })
    const { forms, audio } = tables(args)
    expect(forms.hu.textSlug).toBe("hungarian")
    // A text entry never moves the reverse table.
    expect(audio.hu).toBe("csango")
  })

  it("lets a curated entry beat the first slug with the same tag", () => {
    const { args } = fixture({ curated: { en: "english", hu: "hungarian" } })
    expect(tables(args).forms.hu.textSlug).toBe("hungarian")
  })

  it("keeps text and audio entries for one tag independent", () => {
    const { args } = fixture({
      curated: { en: "english", es: "spanish-latin-american" },
      overrides: {
        text: { es: entry("spanish-castilian") },
        audio: { es: entry("spanish-latin-american") },
        forYou: {},
      },
    })
    const { forms, audio } = tables(args)
    expect(forms.es.textSlug).toBe("spanish-castilian")
    expect(forms.es.rawTag).toBe("es-ES")
    expect(audio.es).toBe("spanish-latin-american")
  })

  it("lets an audio override beat the first slug and add a phone-only key", () => {
    const { args } = fixture({
      overrides: {
        ...BASE_OVERRIDES,
        audio: {
          hu: entry("hungarian"),
          "es-es": entry("spanish-castilian"),
          ne: entry("english"),
        },
      },
    })
    const { forms, audio } = tables(args)
    expect(audio.hu).toBe("hungarian")
    expect(audio["es-es"]).toBe("spanish-castilian")
    expect(audio.ne).toBe("english")
    // An audio entry never moves a text slug.
    expect(forms.hu.textSlug).toBe("csango")
  })

  it("lists only the audio overrides as reviewed", () => {
    const { args } = fixture({
      overrides: {
        ...BASE_OVERRIDES,
        text: { hu: entry("hungarian") },
        audio: {
          hu: entry("hungarian"),
          "es-es": entry("spanish-castilian"),
        },
      },
    })
    const { audio, reviewedAudio } = tables(args)
    expect(reviewedAudio).toEqual({
      "es-es": "spanish-castilian",
      hu: "hungarian",
    })
    // Admin's own tags go only to the full reverse table.
    expect(audio.ha).toBe("hausa")
    expect(audio["es-es"]).toBe("spanish-castilian")
  })

  it("writes the reviewed table into the generated file", () => {
    const { args, outFile } = fixture({
      overrides: {
        ...BASE_OVERRIDES,
        audio: { "es-es": entry("spanish-castilian") },
      },
    })
    expect(runGenerator(args).status).toBe(0)
    const source = fs.readFileSync(outFile, "utf8")
    expect(source).toMatch(
      /export const REVIEWED_AUDIO_SLUG_BY_TAG[^=]*= \{\s*"es-es": "spanish-castilian",\s*\}/,
    )
  })

  it("keys the reverse table on the lowercase Admin tag", () => {
    const { audio } = tables(fixture().args)
    expect(audio["es-es"]).toBe("spanish-castilian")
    expect(audio["es-ES"]).toBeUndefined()
  })

  it("keeps Admin's exact case in the raw tag", () => {
    const { args } = fixture({
      curated: { en: "english", es: "spanish-castilian" },
    })
    expect(tables(args).forms.es.rawTag).toBe("es-ES")
  })

  it("sets the For You locale from its override, else the catalog tag", () => {
    const { args } = fixture({
      catalogs: ["en", "tl"],
      map: [...BASE_MAP, ["tagalog", "fil"]],
      curated: { en: "english", tl: "tagalog" },
      overrides: {
        ...BASE_OVERRIDES,
        forYou: { tl: { locale: "fil", reason: "Fixture." } },
      },
    })
    const { forms } = tables(args)
    expect(forms.tl).toEqual({
      catalogTag: "tl",
      forYouLocale: "fil",
      textSlug: "tagalog",
      rawTag: "fil",
    })
    expect(forms.en.forYouLocale).toBe("en")
  })

  it("gives an unmapped catalog English content, never a null slug", () => {
    const { forms, englishContent } = tables(fixture().args)
    expect(forms.ab).toEqual({
      catalogTag: "ab",
      forYouLocale: "ab",
      textSlug: "english",
      rawTag: "en",
    })
    expect(englishContent).toEqual(["ab"])
  })

  it("refuses an override slug that is not in the web map", () => {
    const { args } = fixture({
      overrides: { ...BASE_OVERRIDES, text: { hu: entry("hungarian-x") } },
    })
    const result = runGenerator(args)
    expect(result.status).toBe(1)
    expect(result.stderr).toContain("hungarian-x")
  })

  it("refuses a text override for a tag that has no catalog", () => {
    const { args } = fixture({
      overrides: { ...BASE_OVERRIDES, text: { xx: entry("hungarian") } },
    })
    const result = runGenerator(args)
    expect(result.status).toBe(1)
    expect(result.stderr).toContain("xx")
  })

  it("refuses an override entry without a reason", () => {
    const { args } = fixture({
      overrides: { ...BASE_OVERRIDES, text: { hu: { slug: "hungarian" } } },
    })
    const result = runGenerator(args)
    expect(result.status).toBe(1)
    expect(result.stderr).toContain("reason")
  })

  it("refuses an audio key that is not a lowercase tag", () => {
    const { args } = fixture({
      overrides: { ...BASE_OVERRIDES, audio: { "es-ES": entry("english") } },
    })
    const result = runGenerator(args)
    expect(result.status).toBe(1)
    expect(result.stderr).toContain("es-ES")
  })

  it("refuses a map whose entry count differs from its header", () => {
    const { args, mapFile } = fixture()
    fs.writeFileSync(mapFile, mapSource(BASE_MAP, BASE_MAP.length + 1))
    const result = runGenerator(args)
    expect(result.status).toBe(1)
    expect(result.stderr).toContain("language-bcp47-map.ts")
  })

  it("refuses a locale.ts without the curated table", () => {
    const { args } = fixture()
    const localeFile = args[0].slice("--web-dir=".length)
    fs.writeFileSync(path.join(localeFile, "src", "lib", "locale.ts"), "\n")
    const result = runGenerator(args)
    expect(result.status).toBe(1)
    expect(result.stderr).toContain(
      "PUBLIC_WATCH_AUDIO_LANGUAGE_SLUG_BY_UI_LOCALE",
    )
  })

  it("finds no app module that imports from apps/web", () => {
    const files = [
      ...sourceFiles(path.join(MOBILE_DIR, "src")),
      ...sourceFiles(path.join(MOBILE_DIR, "app")),
    ]
    // A floor, so a broken walk cannot pass by scanning nothing.
    expect(files.length).toBeGreaterThan(100)
    const offenders = files
      .filter((file) => !file.includes(`${path.sep}__tests__${path.sep}`))
      .filter((file) => WEB_IMPORT.test(fs.readFileSync(file, "utf8")))
      .map((file) => path.relative(MOBILE_DIR, file))
    expect(offenders).toEqual([])
  })

  it("flags an import from apps/web (positive control)", () => {
    expect(WEB_IMPORT.test(`import { x } from "../../../web/src/lib/x"`)).toBe(
      true,
    )
    expect(WEB_IMPORT.test(`import { x } from "../lib/webLinks"`)).toBe(false)
    expect(WEB_IMPORT.test(`import { x } from "@forge/web/lib/locale"`)).toBe(
      true,
    )
    expect(WEB_IMPORT.test(`require("../../apps/web/src/lib/locale")`)).toBe(
      true,
    )
  })
})
