-- Add compact provenance for experience vectors generated by Mastra and
-- stored by Admin. Nullable columns preserve existing ExperienceLocale rows
-- written by the previous admin-native provider path.

ALTER TABLE "experience_locale"
  ADD COLUMN "embedding_source_content_hash" text,
  ADD COLUMN "embedding_source_summary" text,
  ADD COLUMN "embedding_model" text,
  ADD COLUMN "embedding_dimensions" integer,
  ADD COLUMN "embedding_provider" text,
  ADD COLUMN "embedding_generation_mode" text,
  ADD COLUMN "embedding_mastra_run_id" text,
  ADD COLUMN "embedding_generated_at" timestamp(3);

CREATE INDEX "experience_locale_embedding_source_content_hash_idx"
  ON "experience_locale"("embedding_source_content_hash");

CREATE INDEX "experience_locale_embedding_mastra_run_id_idx"
  ON "experience_locale"("embedding_mastra_run_id");
