export const copy = {
  en: {
    brand: "JESUS Film Project",
    title: "Help us improve Watch",
    intro:
      "Tell us what happened on your TV. You can add a photo or video from your phone.",
    stages: ["Tell us", "Evidence", "TV details", "Review"],
    category: "What would you like to share?",
    categories: {
      problem: "Something broke",
      confusing: "Something was confusing",
      idea: "An idea",
      praise: "Something worked well",
    },
    message: "What happened?",
    expected: "What did you expect? (optional)",
    steps: "How can we repeat it? (optional)",
    blocked: "I could not continue watching",
    evidence: "Show us what you saw",
    evidenceHint:
      "Add up to three photos or one short video. Photos can be marked up before you send.",
    photo: "Add photos",
    video: "Add a video",
    edit: "Mark photo",
    remove: "Remove",
    upload: "Uploading",
    ready: "Ready to send",
    retry: "Try again",
    camera: "Take a photo",
    detailTitle: "Which TV was affected?",
    platform: "Platform",
    feature: "Where did this happen?",
    film: "Film title (optional)",
    audio: "Audio language (optional)",
    subtitle: "Subtitle language (optional)",
    review: "Review your report",
    reviewHint:
      "Only the images you preview here will be sent to our team. Your phone's browser details are separate from the TV details.",
    name: "Your name (optional)",
    email: "Email for follow-up (optional)",
    phoneConsent: "Include my phone's browser details",
    uploadNotice:
      "Selected files are stored privately while you prepare this report. They reach the feedback team only after you select Send.",
    next: "Continue",
    back: "Back",
    send: "Send feedback",
    sending: "Sending…",
    preparingEvidence: "Preparing your photo or video…",
    success: "Feedback received",
    successHint:
      "Thank you. Your report is saved. This page will show when it reaches our team.",
    checkStatus: "Check delivery status",
    delivered: "Delivered to the team",
    processing: "Still processing evidence",
    issue: "Delivery needs attention",
    error: "Something went wrong. Your text is still here; please try again.",
    editor: "Mark this photo",
    select: "Select",
    deleteMark: "Delete mark",
    selectedMark: "Selected mark",
    moveHint: "Drag to move. Tap the bin to delete.",
    draw: "Draw",
    arrow: "Arrow",
    box: "Box",
    text: "Text",
    redact: "Cover",
    undo: "Undo",
    redo: "Redo",
    save: "Save photo",
    cancel: "Cancel",
    textPrompt: "Enter a label",
    addText: "Add text",
    noFile: "No files added",
    language: "Language",
    uploadFailure:
      "This file could not be uploaded. Try it again or remove it.",
  },
  th: {
    brand: "Jesus Film Project",
    title: "ช่วยพัฒนา Watch",
    intro:
      "เล่าให้เราฟังว่าเกิดอะไรขึ้นบนทีวี คุณแนบรูปหรือวิดีโอจากโทรศัพท์ได้",
    stages: ["เล่าให้ฟัง", "หลักฐาน", "ข้อมูลทีวี", "ตรวจและส่ง"],
    category: "คุณต้องการบอกอะไรเรา?",
    categories: {
      problem: "พบปัญหา",
      confusing: "ใช้งานแล้วสับสน",
      idea: "มีข้อเสนอแนะ",
      praise: "สิ่งที่ทำได้ดี",
    },
    message: "เกิดอะไรขึ้น?",
    expected: "คุณคาดว่าจะเกิดอะไรขึ้น? (ไม่บังคับ)",
    steps: "ทำอย่างไรจึงเกิดปัญหานี้? (ไม่บังคับ)",
    blocked: "ฉันไม่สามารถดูวิดีโอต่อได้",
    evidence: "แสดงสิ่งที่คุณพบ",
    evidenceHint:
      "แนบรูปได้สูงสุด 3 รูปหรือวิดีโอสั้น 1 คลิป และทำเครื่องหมายบนรูปก่อนส่งได้",
    photo: "เพิ่มรูป",
    video: "เพิ่มวิดีโอ",
    edit: "ทำเครื่องหมาย",
    remove: "ลบ",
    upload: "กำลังอัปโหลด",
    ready: "พร้อมส่ง",
    retry: "ลองอีกครั้ง",
    camera: "ถ่ายรูป",
    detailTitle: "ทีวีเครื่องไหนที่มีปัญหา?",
    platform: "แพลตฟอร์ม",
    feature: "เกิดปัญหาที่ส่วนไหน?",
    film: "ชื่อภาพยนตร์ (ไม่บังคับ)",
    audio: "ภาษาเสียง (ไม่บังคับ)",
    subtitle: "ภาษาคำบรรยาย (ไม่บังคับ)",
    review: "ตรวจสอบก่อนส่ง",
    reviewHint:
      "ทีมงานจะได้รับเฉพาะรูปที่คุณเห็นในหน้านี้ ข้อมูลเบราว์เซอร์บนโทรศัพท์แยกจากข้อมูลทีวี",
    name: "ชื่อ (ไม่บังคับ)",
    email: "อีเมลสำหรับติดต่อกลับ (ไม่บังคับ)",
    phoneConsent: "แนบข้อมูลเบราว์เซอร์ของโทรศัพท์",
    uploadNotice:
      "ไฟล์จะถูกเก็บชั่วคราวแบบส่วนตัวระหว่างเตรียมรายงาน และจะส่งให้ทีมเมื่อคุณกดส่งเท่านั้น",
    next: "ต่อไป",
    back: "กลับ",
    send: "ส่งความคิดเห็น",
    sending: "กำลังส่ง…",
    preparingEvidence: "กำลังเตรียมรูปหรือวิดีโอ…",
    success: "ได้รับความคิดเห็นแล้ว",
    successHint:
      "ขอบคุณ รายงานของคุณถูกบันทึกแล้ว หน้านี้จะแสดงเมื่อส่งถึงทีมงาน",
    checkStatus: "ตรวจสถานะ",
    delivered: "ส่งถึงทีมแล้ว",
    processing: "กำลังประมวลผลไฟล์",
    issue: "การส่งต้องตรวจสอบ",
    error: "เกิดข้อผิดพลาด ข้อความของคุณยังอยู่ กรุณาลองอีกครั้ง",
    editor: "ทำเครื่องหมายบนรูป",
    select: "เลือก",
    deleteMark: "ลบเครื่องหมาย",
    selectedMark: "เครื่องหมายที่เลือก",
    moveHint: "ลากเพื่อย้าย กดไอคอนถังขยะเพื่อลบ",
    draw: "วาด",
    arrow: "ลูกศร",
    box: "กรอบ",
    text: "ข้อความ",
    redact: "ปิดทับ",
    undo: "ย้อนกลับ",
    redo: "ทำซ้ำ",
    save: "บันทึกรูป",
    cancel: "ยกเลิก",
    textPrompt: "พิมพ์ข้อความ",
    addText: "เพิ่มข้อความ",
    noFile: "ยังไม่มีไฟล์",
    language: "ภาษา",
    uploadFailure: "อัปโหลดไฟล์นี้ไม่ได้ โปรดลองอีกครั้งหรือลบไฟล์",
  },
} as const

export type UiLanguage = keyof typeof copy
