/** Display membership only. Never use these IDs in retrieval or consumer policy. */
export type PortalSourceBrand = {
  id: string
  name: string
  sourceKeys: readonly string[]
}

export const portalSourceBrands: readonly PortalSourceBrand[] = [
  {
    id: "everystudent",
    name: "EveryStudent",
    sourceKeys: [
      "everystudent",
      "everystudent-am",
      "everystudent-ar",
      "everystudent-bg",
      "everystudent-bn",
      "everystudent-cs",
      "everystudent-de",
      "everystudent-el",
      "everystudent-es",
      "everystudent-et",
      "everystudent-fa",
      "everystudent-fr",
      "everystudent-he",
      "everystudent-hi",
      "everystudent-hr",
      "everystudent-hu",
      "everystudent-hy",
      "everystudent-id",
      "everystudent-it",
      "everystudent-ja",
      "everystudent-ka",
      "everystudent-kk",
      "everystudent-ko",
      "everystudent-lt",
      "everystudent-mk",
      "everystudent-mn",
      "everystudent-ms",
      "everystudent-my",
      "everystudent-ne",
      "everystudent-om",
      "everystudent-pl",
      "everystudent-pt",
      "everystudent-ro",
      "everystudent-ru",
      "everystudent-ru-ca",
      "everystudent-sk",
      "everystudent-sl",
      "everystudent-sq",
      "everystudent-sr",
      "everystudent-sw",
      "everystudent-ta",
      "everystudent-te",
      "everystudent-th",
      "everystudent-ti",
      "everystudent-tr",
      "everystudent-uk",
      "everystudent-ur",
      "everystudent-vi",
      "everystudent-zh-cn",
      "everystudent-zh-tw",
    ],
  },
  {
    id: "thelife",
    name: "thelife",
    sourceKeys: ["thelife", "thelife-fr", "thelife-zh"],
  },
]
