WITH r AS MATERIALIZED (SELECT id,locale,seed_media_id,expected_item_count,served_item_payload FROM recommendation_request WHERE surface_version='watch-below-player-v1' AND created_at>='2026-09-29T18:42:00Z' AND created_at<'2026-09-30T18:42:00Z' AND expected_item_count>0), contexts AS MATERIALIZED (
SELECT r.*,coalesce(r.served_item_payload->'items'->i.id->'presentation',i.presentation)->>'audioLanguageSlug' audio_language_slug FROM r CROSS JOIN LATERAL (SELECT id,presentation FROM recommendation_served_item WHERE request_id=r.id ORDER BY position LIMIT 1) i)
SELECT r.locale,r.audio_language_slug,exists(SELECT 1 FROM recommendation_curated_pointer p JOIN recommendation_curated_pool cp ON cp.generation_id=p.generation_id WHERE cp.pool_key='start' AND cp.locale=r.locale AND cp.audio_language_slug=r.audio_language_slug) has_current_pool,count(*) requests,count(*) FILTER(WHERE expected_item_count<6) partial,min(expected_item_count) min_cards,max(expected_item_count) max_cards FROM contexts r GROUP BY 1,2,3 ORDER BY partial DESC,requests DESC;
SELECT locale,status,count(*) rows,count(DISTINCT video_id) videos FROM video_locale WHERE locale IN ('en','te','zh','ckb','fr','ro','ta','am','sw') AND deleted_at IS NULL GROUP BY 1,2 ORDER BY 1,2;
WITH bad AS MATERIALIZED (SELECT locale,seed_media_id,fallback_reason,count(*) requests FROM recommendation_request WHERE surface_version='watch-below-player-v1' AND created_at>='2026-09-29T18:42:00Z' AND created_at<'2026-09-30T18:42:00Z' AND expected_item_count=0 GROUP BY 1,2,3), status AS (
SELECT b.*, exists(SELECT 1 FROM video_transcript t WHERE t.video_id=b.seed_media_id AND t.language=b.locale) has_transcript,
exists(SELECT 1 FROM video_transcript t JOIN video_transcript_chunk ch ON ch.transcript_id=t.id CROSS JOIN content_embedding_contract_pointer p JOIN content_embedding_contract c ON c.id=p.active_contract_id WHERE t.video_id=b.seed_media_id AND t.language=b.locale AND ch.language=b.locale AND ch.embedding IS NOT NULL AND t.embedding_provider=c.storage_provider AND t.model=c.storage_model AND t.dimensions=c.storage_dimensions AND t.embedding_native_dimensions=c.storage_native_dimensions AND t.embedding_transform_version IS NOT DISTINCT FROM c.storage_transform_version AND ch.model=c.storage_model AND ch.dimensions=c.storage_dimensions) has_active_seed,
exists(SELECT 1 FROM video_locale vl WHERE vl.locale=b.locale AND vl.status='published' AND vl.deleted_at IS NULL) locale_has_published_content
FROM bad b)
SELECT locale,fallback_reason,has_transcript,has_active_seed,locale_has_published_content,sum(requests) requests,count(*) seed_contexts FROM status GROUP BY 1,2,3,4,5 ORDER BY requests DESC;
