// Generated by scripts/i18n/generate-catalog-index.mjs. Do not edit.
// Run `node scripts/i18n/generate-catalog-index.mjs` after a catalog change.
/* eslint-disable @typescript-eslint/no-require-imports */

export const CATALOG_TAGS = ["en"] as const

export type CatalogTag = (typeof CATALOG_TAGS)[number]

// A thunk keeps its catalog in the bundle but off the heap until it runs (R8).
export const CATALOG_LOADERS: Record<CatalogTag, () => object> = {
  en: () => require("../../messages/en.json"),
}
