// Generated by scripts/i18n/generate-catalog-index.mjs. Do not edit.
// Run `node scripts/i18n/generate-catalog-index.mjs` after a catalog change.
/* eslint-disable @typescript-eslint/no-require-imports */

import type { CatalogTag } from "./catalogs.generated"

export const PLURAL_DATA_TAGS = ["en"] as const

export type PluralDataTag = (typeof PLURAL_DATA_TAGS)[number]

// The exact CLDR data tag each catalog formats plurals under (KTD1).
export const PLURAL_DATA_TAG: Record<CatalogTag, PluralDataTag> = {
  en: "en",
}

export const PLURAL_DATA_LOADERS: Record<PluralDataTag, () => void> = {
  en: () => require("@formatjs/intl-pluralrules/locale-data/en.js"),
}
