WITH r AS MATERIALIZED (SELECT r.id,r.seed_media_id,r.created_at,p.projection_generation_id FROM recommendation_request r JOIN recommendation_personalization_decision p ON p.request_id=r.id WHERE p.execution_mode='hybrid_personalized' AND r.created_at>='2026-09-08T01:45:00Z' AND r.created_at<'2026-09-15T01:45:00Z'), f AS MATERIALIZED (
SELECT r.id request_id,r.seed_media_id,r.projection_generation_id,i.id item_id,i.target_media_id,i.position,i.presentation,
EXISTS(SELECT 1 FROM jsonb_array_elements(i.candidate_provenance->'sources') s WHERE s->>'generator'='multi-interest-profile' AND s->>'rejectionReason' IS NULL) profile_source,
EXISTS(SELECT 1 FROM jsonb_array_elements(i.candidate_provenance->'sources') s WHERE s->>'generator'='semantic' AND s->>'rejectionReason' IS NULL) semantic_source,
(SELECT max((s->>'sourceScore')::float) FROM jsonb_array_elements(i.candidate_provenance->'sources') s WHERE s->>'generator'='multi-interest-profile' AND s->>'rejectionReason' IS NULL) profile_similarity,
EXISTS(SELECT 1 FROM recommendation_profile_projection_contribution c WHERE c.generation_id=r.projection_generation_id AND c.kind='qualified_outcome' AND c.target_media_id=i.target_media_id) previously_learned_video,
EXISTS(SELECT 1 FROM recommendation_profile_projection_contribution c WHERE c.generation_id=r.projection_generation_id AND c.kind='qualified_outcome' AND c.target_media_id=i.target_media_id AND c.occurred_at>r.created_at-interval '24 hours') learned_last_24h
FROM r JOIN recommendation_served_item i ON i.request_id=r.id), slates AS MATERIALIZED (
SELECT request_id,count(*) cards,count(distinct target_media_id) distinct_videos,count(*) FILTER(WHERE profile_source) profile_cards,count(*) FILTER(WHERE semantic_source) semantic_cards FROM f GROUP BY 1)
SELECT count(*) slates,count(*) FILTER(WHERE cards=6) six_cards,count(*) FILTER(WHERE cards<>distinct_videos) duplicate_video_slates,count(*) FILTER(WHERE profile_cards=0) without_profile_contribution,count(*) FILTER(WHERE semantic_cards=0) without_semantic_contribution,avg(profile_cards) mean_profile_contributed_cards FROM slates;
WITH r AS MATERIALIZED (SELECT r.id,r.seed_media_id,r.created_at,p.projection_generation_id FROM recommendation_request r JOIN recommendation_personalization_decision p ON p.request_id=r.id WHERE p.execution_mode='hybrid_personalized' AND r.created_at>='2026-09-08T01:45:00Z' AND r.created_at<'2026-09-15T01:45:00Z'), f AS MATERIALIZED (
SELECT i.id,i.target_media_id,r.seed_media_id,
EXISTS(SELECT 1 FROM jsonb_array_elements(i.candidate_provenance->'sources') s WHERE s->>'generator'='multi-interest-profile' AND s->>'rejectionReason' IS NULL) profile_source,
EXISTS(SELECT 1 FROM jsonb_array_elements(i.candidate_provenance->'sources') s WHERE s->>'generator'='semantic' AND s->>'rejectionReason' IS NULL) semantic_source,
(SELECT max((s->>'sourceScore')::float) FROM jsonb_array_elements(i.candidate_provenance->'sources') s WHERE s->>'generator'='multi-interest-profile' AND s->>'rejectionReason' IS NULL) profile_similarity,
EXISTS(SELECT 1 FROM recommendation_profile_projection_contribution c WHERE c.generation_id=r.projection_generation_id AND c.kind='qualified_outcome' AND c.target_media_id=i.target_media_id) previously_learned_video,
EXISTS(SELECT 1 FROM recommendation_profile_projection_contribution c WHERE c.generation_id=r.projection_generation_id AND c.kind='qualified_outcome' AND c.target_media_id=i.target_media_id AND c.occurred_at>r.created_at-interval '24 hours') learned_last_24h
FROM r JOIN recommendation_served_item i ON i.request_id=r.id)
SELECT profile_source,semantic_source,count(*) cards,count(*) FILTER(WHERE target_media_id=seed_media_id) same_as_current_video,count(*) FILTER(WHERE previously_learned_video) previously_learned_video,count(*) FILTER(WHERE learned_last_24h) learned_last_24h,percentile_cont(0.5) within group(order by profile_similarity) profile_similarity_p50,percentile_cont(0.1) within group(order by profile_similarity) profile_similarity_p10 FROM f GROUP BY 1,2;
