-- Current active profiles; identifiers and viewing histories remain inside PostgreSQL.
WITH interests AS MATERIALIZED (SELECT generation_id,count(*) FILTER(WHERE expires_at>'2026-09-15T02:03:52.496Z') live_interests,count(*) FILTER(WHERE kind='durable' AND expires_at>'2026-09-15T02:03:52.496Z') live_durable,count(*) FILTER(WHERE kind='session' AND expires_at>'2026-09-15T02:03:52.496Z') live_session FROM recommendation_profile_interest GROUP BY 1), p AS MATERIALIZED (
 SELECT p.id,p.created_at,p.updated_at,g.id generation_id,g.contribution_count,g.generation,g.input_watermark,g.published_at,g.expires_at generation_expires,i.live_interests,i.live_durable,i.live_session
 FROM recommendation_profile p LEFT JOIN recommendation_profile_projection_pointer ptr ON ptr.profile_id=p.id AND ptr.privacy_generation=p.privacy_generation AND ptr.scope='durable'
 LEFT JOIN recommendation_profile_projection_generation g ON g.id=ptr.generation_id AND g.state='published' AND g.profile_id=p.id AND g.privacy_generation=p.privacy_generation
 LEFT JOIN interests i ON i.generation_id=g.id WHERE p.state='active' AND p.expires_at>'2026-09-15T02:03:52.496Z' AND p.created_at<'2026-09-15T02:03:52.496Z')
SELECT count(*) active_profiles,count(*) FILTER(WHERE generation_id IS NULL) no_projection,count(*) FILTER(WHERE generation_id IS NOT NULL AND contribution_count=0) empty_projection,count(*) FILTER(WHERE live_interests>0 AND generation_expires>'2026-09-15T02:03:52.496Z') usable_profiles,count(*) FILTER(WHERE live_durable>0) durable_profiles,count(*) FILTER(WHERE live_session>0) session_signal_profiles,count(*) FILTER(WHERE contribution_count>0 AND coalesce(live_interests,0)=0) contributed_but_no_live_interest,count(*) FILTER(WHERE generation>1 AND contribution_count>0) populated_with_multiple_generations,percentile_cont(0.5) within group(order by contribution_count) FILTER(WHERE live_interests>0) populated_median_contributions,percentile_cont(0.95) within group(order by contribution_count) FILTER(WHERE live_interests>0) populated_p95_contributions FROM p;
WITH g AS (SELECT g.* FROM recommendation_profile_projection_pointer ptr JOIN recommendation_profile_projection_generation g ON g.id=ptr.generation_id JOIN recommendation_profile p ON p.id=g.profile_id AND p.privacy_generation=g.privacy_generation WHERE p.state='active' AND p.expires_at>'2026-09-15T02:03:52.496Z' AND g.expires_at>'2026-09-15T02:03:52.496Z' AND g.contribution_count>0)
SELECT durable_interest_count,session_intent_present,count(*) profiles,min(contribution_count) minimum_contributions,percentile_cont(0.5) within group(order by contribution_count) median_contributions,max(contribution_count) maximum_contributions FROM g GROUP BY 1,2 ORDER BY 1,2;
WITH g AS MATERIALIZED (SELECT g.* FROM recommendation_profile_projection_pointer ptr JOIN recommendation_profile_projection_generation g ON g.id=ptr.generation_id JOIN recommendation_profile p ON p.id=g.profile_id AND p.privacy_generation=g.privacy_generation WHERE p.state='active' AND p.expires_at>'2026-09-15T02:03:52.496Z' AND g.expires_at>'2026-09-15T02:03:52.496Z' AND g.contribution_count>0)
SELECT c.kind,count(*) contributions,count(distinct g.id) profiles,count(*) FILTER(WHERE c.kind='qualified_outcome' AND o.id IS NULL) missing_outcome,count(*) FILTER(WHERE c.kind='qualified_outcome' AND o.id IS NOT NULL AND NOT o.qualified_view) unqualified_outcome,count(*) FILTER(WHERE c.kind='qualified_outcome' AND o.classifier_version<>'active-watch-proxy-v1') wrong_classifier,count(*) FILTER(WHERE c.kind='qualified_outcome' AND e.state NOT IN ('finalized','timed_out')) unfinished_episode,count(*) FILTER(WHERE c.kind='qualified_outcome' AND c.target_media_id<>e.media_id) wrong_media,count(*) FILTER(WHERE c.kind='qualified_outcome' AND c.privacy_generation<>g.privacy_generation) wrong_privacy_generation,count(*) FILTER(WHERE c.expires_at<='2026-09-15T02:03:52.496Z') expired_contributions FROM g JOIN recommendation_profile_projection_contribution c ON c.generation_id=g.id LEFT JOIN recommendation_outcome_revision o ON o.id=c.source_outcome_id LEFT JOIN recommendation_playback_episode e ON e.id=o.episode_id GROUP BY 1;
SELECT g.scope,count(*) personalized_requests,count(distinct g.profile_id) profiles,count(distinct g.id) used_generations,count(*) FILTER(WHERE g.id IS NULL) missing_projection,count(*) FILTER(WHERE g.expires_at<=r.created_at) expired_when_used,count(*) FILTER(WHERE g.published_at>r.created_at) published_after_request,count(*) FILTER(WHERE p.interest_count=0) zero_interest_count,percentile_cont(0.5) within group(order by p.profile_retrieval_latency_ms) retrieval_p50_ms,percentile_cont(0.95) within group(order by p.profile_retrieval_latency_ms) retrieval_p95_ms FROM recommendation_personalization_decision p JOIN recommendation_request r ON r.id=p.request_id LEFT JOIN recommendation_profile_projection_generation g ON g.id=p.projection_generation_id WHERE p.execution_mode='hybrid_personalized' AND r.created_at>='2026-09-08T01:45:00Z' AND r.created_at<'2026-09-15T01:45:00Z' GROUP BY 1;
