-- Live persisted delivery evidence; aggregate repeat behavior without exporting profile histories.
WITH r AS MATERIALIZED (SELECT r.id,r.created_at,p.projection_generation_id FROM recommendation_request r JOIN recommendation_personalization_decision p ON p.request_id=r.id WHERE p.execution_mode='hybrid_personalized' AND r.created_at>='2026-09-08T01:45:00Z' AND r.created_at<'2026-09-15T01:45:00Z' ORDER BY r.created_at DESC,r.id DESC LIMIT 200), repeats AS MATERIALIZED (
 SELECT i.id item_id,r.id request_id,i.target_media_id,i.candidate_generator,bool_or(e.discovery_source<>'recommendation') learned_outside_recommendations,bool_or(e.discovery_source='recommendation') learned_from_recommendation
 FROM r JOIN recommendation_served_item i ON i.request_id=r.id JOIN recommendation_profile_projection_contribution c ON c.generation_id=r.projection_generation_id AND c.target_media_id=i.target_media_id AND c.kind='qualified_outcome' AND c.occurred_at>r.created_at-interval '24 hours'
 JOIN recommendation_outcome_revision o ON o.id=c.source_outcome_id JOIN recommendation_playback_episode e ON e.id=o.episode_id GROUP BY 1,2,3,4
), f AS MATERIALIZED (
 SELECT repeats.*,EXISTS(SELECT 1 FROM recommendation_candidate_run cr JOIN recommendation_candidate_stage_evidence se ON se.run_id=cr.id AND se.stage='rejected' AND se.reason_codes && ARRAY['recent_playback_start','recent_selection','repeatedly_served']::text[] AND se.target_media_id=repeats.target_media_id WHERE cr.request_id=repeats.request_id) suppression_recorded,
 EXISTS(SELECT 1 FROM recommendation_candidate_run cr JOIN recommendation_candidate_stage_evidence se ON se.run_id=cr.id AND se.stage='composed' AND se.target_media_id=repeats.target_media_id AND 'refill_after_suppression'=ANY(se.reason_codes) WHERE cr.request_id=repeats.request_id) refill_or_movement_recorded FROM repeats
)
SELECT candidate_generator,learned_outside_recommendations,learned_from_recommendation,count(*) repeat_cards,count(distinct request_id) affected_requests,count(*) FILTER(WHERE suppression_recorded) suppression_recorded,count(*) FILTER(WHERE refill_or_movement_recorded) refill_or_movement_recorded FROM f GROUP BY 1,2,3 ORDER BY repeat_cards DESC;
