import { createHash } from "node:crypto"

import type { SupportResearchConfig } from "../../config/env"
import {
  supportActionDraftSchema,
  type StoredSupportObservation,
  type SupportActionDraft,
} from "./schema"

export type SupportActionDecision =
  | { action: SupportActionDraft; reason: "policy_passed" }
  | {
      action?: undefined
      reason:
        | "not_relevant"
        | "below_confidence"
        | "below_actionability"
        | "below_recurrence"
        | "unsupported_kind"
    }

export function safeLinearText(value: string): string {
  return value
    .replace(/<!--[\s\S]*?-->/gu, " ")
    .replace(/https?:\/\/[^\s]+/giu, "[URL omitted]")
    .replace(/[\p{Cc}\p{Cf}]+/gu, " ")
    .replace(/[\\`*_<>#|@]/gu, "\\$&")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replace(/\s+/gu, " ")
    .trim()
}

function actionFingerprint(type: string, themeFingerprint: string): string {
  return createHash("sha256")
    .update(`v1\0${type}\0${themeFingerprint}`)
    .digest("hex")
}

function sourceLine(observation: StoredSupportObservation): string {
  return observation.source.sourceUrl
    ? `- [Help Scout conversation ${observation.source.sourceId}](${observation.source.sourceUrl})`
    : `- Help Scout conversation ${observation.source.sourceId}`
}

function issueDescription(input: {
  type: "confirmed_bug" | "needs_validation" | "ux_improvement"
  observations: StoredSupportObservation[]
  idempotencyKey: string
}): string {
  const primary = input.observations[0]
  if (!primary) throw new Error("support action requires an observation")
  const reported = primary.analysis.reportedEvidence
    .map((item) => `- ${safeLinearText(item)}`)
    .join("\n")
  const automated = primary.validation.evidence.length
    ? primary.validation.evidence.map((item) => `- ${item}`).join("\n")
    : "- No deterministic validation evidence was available."
  const missingProof =
    primary.validation.missingProof ??
    "No additional proof is missing from the bounded validator."

  return [
    "> Generated by the Forge Support and User Research Agent. A human remains accountable for validation, priority, assignment, and resolution.",
    "",
    "## Finding",
    safeLinearText(primary.analysis.summary),
    "",
    "## User-reported evidence",
    reported || "- No safe verbatim evidence was retained.",
    "",
    "## Automated checks",
    automated,
    "",
    `**Validation state:** ${primary.validation.state}`,
    `**Missing proof:** ${safeLinearText(missingProof)}`,
    `**Model confidence:** ${primary.analysis.confidence.toFixed(2)}`,
    `**Actionability:** ${primary.analysis.actionability.toFixed(2)}`,
    "",
    "## Sources",
    ...input.observations.map(sourceLine),
    "",
    "## Next human action",
    input.type === "confirmed_bug"
      ? "Confirm product impact and route the reproducible defect through normal triage."
      : input.type === "needs_validation"
        ? "Reproduce the interaction in the reported context before treating it as confirmed."
        : "Review the recurring user-flow friction and decide whether discovery or design work should begin.",
    "",
    `<!-- support-research-key:${input.idempotencyKey} -->`,
  ].join("\n")
}

function draftAction(input: {
  type: "confirmed_bug" | "needs_validation" | "ux_improvement"
  observations: StoredSupportObservation[]
  labelId?: string
}): SupportActionDraft {
  const primary = input.observations[0]
  if (!primary) throw new Error("support action requires an observation")
  const fingerprint = actionFingerprint(input.type, primary.fingerprint)
  const idempotencyKey = `support-research:${input.type}:${fingerprint}`
  const prefix =
    input.type === "needs_validation"
      ? "[Needs validation] "
      : input.type === "ux_improvement"
        ? "[User research] "
        : ""
  return supportActionDraftSchema.parse({
    idempotencyKey,
    fingerprint,
    type: input.type,
    title: `${prefix}${safeLinearText(primary.analysis.title)}`.slice(0, 200),
    description: issueDescription({
      type: input.type,
      observations: input.observations,
      idempotencyKey,
    }),
    labelId: input.labelId,
    sourceIds: [
      ...new Set(input.observations.map((item) => item.source.sourceId)),
    ],
  })
}

export function decideSupportAction(input: {
  observation: StoredSupportObservation
  cluster: StoredSupportObservation[]
  config: Pick<
    SupportResearchConfig,
    | "confirmedConfidence"
    | "inferredConfidence"
    | "improvementActionability"
    | "improvementDistinctSources"
    | "linear"
  >
}): SupportActionDecision {
  const { observation } = input
  if (!observation.analysis.relevant) return { reason: "not_relevant" }

  if (observation.analysis.kind === "bug") {
    if (
      observation.validation.state === "confirmed" &&
      observation.analysis.confidence >= input.config.confirmedConfidence
    ) {
      return {
        action: draftAction({
          type: "confirmed_bug",
          observations: [observation],
          labelId: input.config.linear.confirmedBugLabelId,
        }),
        reason: "policy_passed",
      }
    }
    if (observation.analysis.confidence < input.config.inferredConfidence) {
      return { reason: "below_confidence" }
    }
    if (
      observation.analysis.actionability < input.config.improvementActionability
    ) {
      return { reason: "below_actionability" }
    }
    return {
      action: draftAction({
        type: "needs_validation",
        observations: [observation],
        labelId: input.config.linear.needsValidationLabelId,
      }),
      reason: "policy_passed",
    }
  }

  if (
    observation.analysis.kind !== "usability" &&
    observation.analysis.kind !== "need"
  ) {
    return { reason: "unsupported_kind" }
  }
  if (
    observation.analysis.actionability < input.config.improvementActionability
  ) {
    return { reason: "below_actionability" }
  }
  const distinct = new Map(
    input.cluster.map((item) => [item.source.sourceId, item]),
  )
  if (distinct.size < input.config.improvementDistinctSources) {
    return { reason: "below_recurrence" }
  }
  return {
    action: draftAction({
      type: "ux_improvement",
      observations: [...distinct.values()],
      labelId: input.config.linear.uxLabelId,
    }),
    reason: "policy_passed",
  }
}
