import { createHash } from "node:crypto"

import {
  supportActionDraftSchema,
  supportRunReportSchema,
  type StoredSupportObservation,
  type SupportActionDraft,
  type SupportRunReport,
} from "./schema"
import { safeLinearText } from "./action-policy"

export function buildDailySummaryAction(input: {
  runKey: string
  date: string
  observations: StoredSupportObservation[]
  createdIssueUrls: string[]
}): SupportActionDraft | undefined {
  const relevant = input.observations.filter((item) => item.analysis.relevant)
  if (relevant.length === 0) return
  const fingerprint = createHash("sha256")
    .update(`v1\0daily_summary\0${input.date}`)
    .digest("hex")
  const idempotencyKey = `support-research:daily-summary:${fingerprint}`
  const themes = relevant
    .slice(0, 20)
    .map(
      (item) =>
        `- **${safeLinearText(item.analysis.title)}** — ${item.validation.state}; confidence ${item.analysis.confidence.toFixed(2)}`,
    )
  const issueLinks = input.createdIssueUrls.length
    ? input.createdIssueUrls.map((url) => `- ${url}`)
    : ["- Product action results are recorded in the durable run report."]
  return supportActionDraftSchema.parse({
    idempotencyKey,
    fingerprint,
    type: "daily_summary",
    title: `Support insights — ${input.date}`,
    description: [
      "> Generated by the Forge Support and User Research Agent. This is a concise index; the durable Mastra report is authoritative.",
      "",
      `**Run:** ${input.runKey}`,
      `**Relevant conversations:** ${relevant.length}`,
      "",
      "## Themes",
      ...themes,
      "",
      "## Product issues",
      ...issueLinks,
      "",
      `<!-- support-research-key:${idempotencyKey} -->`,
    ].join("\n"),
    sourceIds: [...new Set(relevant.map((item) => item.source.sourceId))].slice(
      0,
      50,
    ),
  })
}

export function buildSupportRunReport(
  input: Omit<SupportRunReport, "findings"> & {
    observations: StoredSupportObservation[]
  },
): SupportRunReport {
  const grouped = new Map<
    string,
    { observation: StoredSupportObservation; sourceIds: Set<string> }
  >()
  for (const observation of input.observations) {
    if (!observation.analysis.relevant) continue
    const current = grouped.get(observation.fingerprint)
    if (current) {
      current.sourceIds.add(observation.source.sourceId)
    } else {
      grouped.set(observation.fingerprint, {
        observation,
        sourceIds: new Set([observation.source.sourceId]),
      })
    }
  }
  return supportRunReportSchema.parse({
    ...input,
    observations: undefined,
    findings: [...grouped.values()].slice(0, 200).map((group) => ({
      fingerprint: group.observation.fingerprint,
      title: group.observation.analysis.title,
      kind: group.observation.analysis.kind,
      validation: group.observation.validation.state,
      sourceCount: group.sourceIds.size,
    })),
  })
}
