// Writes systems.generated.ts, the 66-book compact form of systems/*.json.
// Usage (from apps/mobile, Node 22.18 or later for .ts imports):
//   node src/lib/bible/versification/generate-systems.mjs [--check]
import { Buffer } from "node:buffer"
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import prettier from "prettier"
import { BIBLE_BOOKS } from "../text/books.ts"
import { STANDARD_SYSTEM_IDS, buildVersificationSystems } from "./compact.ts"

const HERE = dirname(fileURLToPath(import.meta.url))
const TARGET = join(HERE, "systems.generated.ts")
const BOOK_IDS = BIBLE_BOOKS.map((book) => book.usfm)

const HEADER = `// Generated by generate-systems.mjs from systems/*.json. Do not edit.
// Data: Copenhagen Alliance versification mappings, CC BY-SA 4.0. See
// systems/LICENSE.md for the source, the authors, and the changes.
`

const raw = Object.fromEntries(
  STANDARD_SYSTEM_IDS.map((id) => [
    id,
    JSON.parse(readFileSync(join(HERE, "systems", `${id}.json`), "utf8")),
  ]),
)
const systems = buildVersificationSystems(raw, BOOK_IDS)

const source = `${HEADER}import type { CompactSystems } from "./compact"

export const VERSIFICATION_SYSTEMS: CompactSystems = ${JSON.stringify(systems)}
`
const options = (await prettier.resolveConfig(TARGET)) ?? {}
const formatted = await prettier.format(source, {
  ...options,
  filepath: TARGET,
})

if (process.argv.includes("--check")) {
  const current = readFileSync(TARGET, "utf8")
  if (current !== formatted) {
    console.error(
      "systems.generated.ts is out of date. Run generate-systems.mjs.",
    )
    process.exit(1)
  }
  console.log("systems.generated.ts is up to date.")
} else {
  writeFileSync(TARGET, formatted)
  console.log(`Wrote ${TARGET} (${Buffer.byteLength(formatted)} bytes).`)
}
