query SyncVideoVariantsCount {
  videoVariantsCount
}

query SyncVideoVariants($limit: Int!, $offset: Int!) {
  videoVariants(limit: $limit, offset: $offset) {
    id
    slug
    duration
    lengthInMilliseconds
    hls
    dash
    share
    downloadable
    published
    brightcoveId
    videoId
    language {
      id
    }
    videoEdition {
      id
      name
    }
    muxVideo {
      id
      assetId
      playbackId
    }
    downloads {
      id
      quality
      size
      height
      width
      bitrate
      url
    }
  }
}
