// Matthew 24:14 from public-domain editions distributed by eBible.org.
// IDs resolve at https://ebible.org/find/show.php?id={id}; the Greek entry is
// the public-domain 1904 Patriarchal Greek New Testament source text.
export type VerseTranslation = {
  id: string
  language: string
  languageInEnglish: string
  text: string
  latitude: number
  longitude: number
  direction: "ltr" | "rtl"
}

export const VERSE_REFERENCE = "Matthew 24:14"
export const VERSE_TRANSLATIONS: readonly VerseTranslation[] = [
  {
    id: "arb-vd",
    language: "العربية",
    languageInEnglish: "Arabic",
    text: "وَيُكْرَزُ بِبِشَارَةِ ٱلْمَلَكُوتِ هَذِهِ فِي كُلِّ ٱلْمَسْكُونَةِ شَهَادَةً لِجَمِيعِ ٱلْأُمَمِ. ثُمَّ يَأْتِي ٱلْمُنْتَهَى.",
    latitude: 24,
    longitude: 45,
    direction: "rtl",
  },
  {
    id: "bla",
    language: "Siksiká",
    languageInEnglish: "Blackfoot",
    text: "Ki am'ok nĭn'naiisĭnni ĭstŏkh'sitsĭniksĭnni ak'anĭstop kŏnŭs'ksŏkkum, kŏnai'okoaua mŏks'ksĭniĭsauaie; ki umuk'itsipi ak'otŭmitoto.",
    latitude: 50,
    longitude: -112,
    direction: "ltr",
  },
  {
    id: "breBRG",
    language: "Brezhoneg",
    languageInEnglish: "Breton",
    text: "An Aviel-mañ eus ar rouantelezh a vo prezeget er bed a-bezh, evit reiñ testeni d'an holl bobloù; neuze e teuio ar fin.",
    latitude: 48,
    longitude: -3,
    direction: "ltr",
  },
  {
    id: "cekak",
    language: "Asang Khongca",
    languageInEnglish: "Chin, Eastern Khumi",
    text: "Acaeng kaminawk boih khaeah hnukung ah oh hanah, hae kahoih siangpahrang ukhaih prae tamthanglok hae long pum ah thuih ah om tih; to pacoengah ni boenghaih to pha vop tih.",
    latitude: 21,
    longitude: 93,
    direction: "ltr",
  },
  {
    id: "ces1613",
    language: "český",
    languageInEnglish: "Czech",
    text: "A budeť kázáno toto evangelium království po všem světě, na svědectví všem národům, a tehdážť přijde skonání.",
    latitude: 50,
    longitude: 15,
    direction: "ltr",
  },
  {
    id: "cha",
    language: "Chamorro",
    languageInEnglish: "Chamorro",
    text: "Ya umapredica este y ebangelion y raeno gui todo y tano, para testimonio gui todo y nasion, ya ayo nae ufato y jinecog.",
    latitude: 13,
    longitude: 145,
    direction: "ltr",
  },
  {
    id: "cmn-cu89s",
    language: "中国语文",
    languageInEnglish: "Chinese",
    text: "这天国的福音要传遍天下，对万民作见证，然后末期才来到。」",
    latitude: 35,
    longitude: 105,
    direction: "ltr",
  },
  {
    id: "copbhc",
    language: "ⲘⲉⲧⲢⲉⲙ̀ⲛⲭⲏⲙⲓ",
    languageInEnglish: "Coptic",
    text: "ⲞⲨⲞϨ ⲈⲨⲈϨⲒⲰⲒϢ ⲘⲠⲀⲒⲈⲨⲀⲄⲄⲈⲖⲒⲞⲚ ⲚⲦⲈϮⲘⲈⲦⲞⲨⲢⲞ ϦⲈⲚϮⲞⲒⲔⲞⲨⲘⲈⲚⲎ ⲦⲎⲢⲤ ⲈⲨⲘⲈⲦⲘⲈⲐⲢⲈ ⲚⲚⲒⲈⲐⲚⲞⲤ ⲦⲎⲢⲞⲨ ⲦⲞⲦⲈ ⲈⲤⲈⲒ ⲚϪⲈϮϦⲀⲎ.",
    latitude: 27,
    longitude: 30,
    direction: "ltr",
  },
  {
    id: "deu1912",
    language: "Deutsch",
    languageInEnglish: "German, Standard",
    text: "Und es wird gepredigt werden das Evangelium vom Reich in der ganzen Welt zu einem Zeugnis über alle Völker, und dann wird das Ende kommen.",
    latitude: 51,
    longitude: 10,
    direction: "ltr",
  },
  {
    id: "dif",
    language: "Dieri",
    languageInEnglish: "Dieri",
    text: "Ja tanali ninapini ngantjani jaura mililandru mita maruni kaukaubala nganai, kana warupotuni malka nganananto, ja ngadani mudani wokarala nganai.",
    latitude: -27,
    longitude: 138,
    direction: "ltr",
  },
  {
    id: "engwebp",
    language: "English",
    languageInEnglish: "English",
    text: "This Good News of the Kingdom will be preached in the whole world for a testimony to all the nations, and then the end will come.",
    latitude: 39,
    longitude: -98,
    direction: "ltr",
  },
  {
    id: "epo",
    language: "Esperanto",
    languageInEnglish: "Esperanto",
    text: "Kaj ĉi tiu evangelio de la regno estos predikita tra la tuta mondo, kiel atesto al ĉiuj nacioj; kaj tiam venos la fino.",
    latitude: 48,
    longitude: 15,
    direction: "ltr",
  },
  {
    id: "fraLSG",
    language: "français",
    languageInEnglish: "French",
    text: "Cette bonne nouvelle du royaume sera prêchée dans le monde entier, pour servir de témoignage à toutes les nations. Alors viendra la fin.",
    latitude: 47,
    longitude: 2,
    direction: "ltr",
  },
  {
    id: "grcbyz",
    language: "Ελληνικά",
    languageInEnglish: "Greek, Ancient",
    text: "καὶ κηρυχθήσεται τοῦτο τὸ εὐαγγέλιον τῆς βασιλείας ἐν ὅλῃ τῇ οἰκουμένῃ εἰς μαρτύριον πᾶσι τοῖς ἔθνεσι, καὶ τότε ἥξει τὸ τέλος.",
    latitude: 39,
    longitude: 22,
    direction: "ltr",
  },
  {
    id: "hat",
    language: "Kreyòl Ayisyen",
    languageInEnglish: "Haitian",
    text: "Fòk yo gen tan mache bay bon nouvèl Peyi kote Bondye Wa a toupatou sou latè, pou tout moun ka tande mesaj la. Se lè sa a atò lafen an va rive.",
    latitude: 19,
    longitude: -72,
    direction: "ltr",
  },
  {
    id: "haw1868",
    language: "'Olelo Hawai'i",
    languageInEnglish: "Hawaiian",
    text: "A e haiia'ku no keia euanelio o ke aupuni ma na wahi aukauaka a pau, i mea e ike ai na lahuikanaka a pau: alaila iho e hiki mai ka hopena.",
    latitude: 20,
    longitude: -156,
    direction: "ltr",
  },
  {
    id: "heb",
    language: "עברית",
    languageInEnglish: "Hebrew",
    text: "ותקרא בשורת המלכות הזאת בתבל כלה לעדות לכל הגוים ואחר יבוא הקץ׃",
    latitude: 32,
    longitude: 35,
    direction: "rtl",
  },
  {
    id: "hlt",
    language: "Matupi Chin",
    languageInEnglish: "Chin, Matu",
    text: "Te phoeiah ram kah olthangthen he namtom boeih taengah laipai la om sak ham lunglai pum boeih ah a hoe ni.Te daengah ni a bawtnah te ha pawk pueng eh.",
    latitude: 21,
    longitude: 94,
    direction: "ltr",
  },
  {
    id: "hrv",
    language: "Hrvatski",
    languageInEnglish: "Croatian",
    text: "“I propovijedat će se ovo evanđelje Kraljevstva po svem svijetu za svjedočanstvo svim narodima. Tada će doći svršetak.”",
    latitude: 45,
    longitude: 16,
    direction: "ltr",
  },
  {
    id: "ita1885",
    language: "Italiano",
    languageInEnglish: "Italian",
    text: "E questo evangelo del regno sarà predicato in tutto il mondo, in testimonianza a tutte le genti; ed allora verrà la fine.",
    latitude: 42,
    longitude: 13,
    direction: "ltr",
  },
  {
    id: "jpn1965",
    language: "日本語",
    languageInEnglish: "Japanese",
    text: "この御国の福音は全世界に宣べ伝えられて、すべての国民にあかしされ、それから、終わりの日が来ます。",
    latitude: 37,
    longitude: 138,
    direction: "ltr",
  },
  {
    id: "kor",
    language: "한국인",
    languageInEnglish: "Korean",
    text: "이 천국 복음이 모든 민족에게 증거되기 위하여 온 세상에 전파되리니 그제야 끝이 오리라",
    latitude: 37,
    longitude: 127,
    direction: "ltr",
  },
  {
    id: "kos",
    language: "Kosrae",
    languageInEnglish: "Kosraean",
    text: "Ac Pweng Wo inge ke Tokosrai uh ac fah lutiyuk fin faclu nufon in mwe loh nu sin mwet nukewa; na faclu fah safla.",
    latitude: 5,
    longitude: 163,
    direction: "ltr",
  },
  {
    id: "latVUC",
    language: "Latine",
    languageInEnglish: "Latin",
    text: "Et prædicabitur hoc Evangelium regni in universo orbe, in testimonium omnibus gentibus: et tunc veniet consummatio.",
    latitude: 42,
    longitude: 12,
    direction: "ltr",
  },
  {
    id: "mya",
    language: "Mynmar language",
    languageInEnglish: "Burmese",
    text: "နိုင်​ငံ​တော်​ဆိုင်​ရာ​သ​တင်း​ကောင်း​အ​ကြောင်း​ကို ကမ္ဘာ​တစ်​ဝန်း​လုံး​ရှိ​လူ​မျိုး​အ​ပေါင်း​တို့​အား သက်​သေ​ခံ​ဟော​ပြော​ပြီး​မှ​ကပ်​ကမ္ဘာ​ကုန်​ဆုံး ချိန်​ရောက်​လိမ့်​မည်။",
    latitude: 21,
    longitude: 96,
    direction: "ltr",
  },
  {
    id: "nld",
    language: "Nederlands",
    languageInEnglish: "Dutch",
    text: "En dit Evangelie des Koninkrijks zal in de gehele wereld gepredikt worden tot een getuigenis allen volken; en dan zal het einde komen.",
    latitude: 52,
    longitude: 5,
    direction: "ltr",
  },
  {
    id: "pesOPV",
    language: "فارسی",
    languageInEnglish: "Persian",
    text: "و به این بشارت ملکوت در تمام عالم موعظه خواهد شد تا بر جمیع امت‌ها شهادتی شود؛ آنگاه انتها خواهد رسید.",
    latitude: 32,
    longitude: 54,
    direction: "rtl",
  },
  {
    id: "pon",
    language: "Pohnpeian",
    languageInEnglish: "Pohnpeian",
    text: "A ronamau en wei o pan kalok jili nan jappa karoj, pwen kaded on wei karoj, iei anjau, me imwi korendo.",
    latitude: 7,
    longitude: 158,
    direction: "ltr",
  },
  {
    id: "porbrbsl",
    language: "Português",
    languageInEnglish: "Portuguese",
    text: "Este Evangelho do Reino será pregado em todo o mundo como testemunho a todas as nações, e então virá o fim.",
    latitude: -10,
    longitude: -52,
    direction: "ltr",
  },
  {
    id: "ron1924",
    language: "Romanian",
    languageInEnglish: "Romanian",
    text: "Евангелияачаста а Ымпэрэцией вафи проповэдуитэ ын тоатэ лумя, ка сэ служяскэ де мэртурие тутурор нямурилор. Атунч ва вени сфыршитул.",
    latitude: 46,
    longitude: 25,
    direction: "ltr",
  },
  {
    id: "russyn",
    language: "русский",
    languageInEnglish: "Russian",
    text: "И проповедано будет сие Евангелие Царствия по всей вселенной, во свидетельство всем народам; и тогда придет конец.",
    latitude: 58,
    longitude: 46,
    direction: "ltr",
  },
  {
    id: "spabll",
    language: "Español",
    languageInEnglish: "Spanish",
    text: "Y estas Buenas Noticias del Reino se anunciarán en todo el mundo, para que todas las naciones las conozcan. Entonces vendrá el fin.",
    latitude: 23,
    longitude: -102,
    direction: "ltr",
  },
  {
    id: "srp1865",
    language: "srpski jezik",
    languageInEnglish: "Serbian",
    text: "I propovediće se ovo jevanđelje o carstvu po svemu svetu za svedočanstvo svim narodima. I tada će doći posledak.",
    latitude: 44,
    longitude: 21,
    direction: "ltr",
  },
  {
    id: "swh1850",
    language: "Kiswahili",
    languageInEnglish: "Swahili",
    text: "Ila, kabla ya mwisho kufika, hii Habari Njema ya Ufalme wa Mungu itahubiriwa ulimwenguni kote kama ushuhuda kwa mataifa yote.",
    latitude: 0,
    longitude: 37,
    direction: "ltr",
  },
  {
    id: "thafb",
    language: "แบบไทย",
    languageInEnglish: "Thai",
    text: "ข่าวดี​เรื่อง​อาณาจักร​นี้​จะ​ได้รับ​การประกาศ​ไป​ทั่ว​โลก เพื่อ​เป็น​พยาน​แก่​ทุกชนชาติ แล้ว​จุดจบ​จะ​มาถึง",
    latitude: 15,
    longitude: 101,
    direction: "ltr",
  },
  {
    id: "ton",
    language: "Tongan",
    languageInEnglish: "Tongan",
    text: "Pea ko e ongoongolelei ni ʻoe puleʻanga ʻe malangaʻaki ʻi māmani kotoa pē, ko e meʻa fakamoʻoni ki he puleʻanga kotoa pē, pea ʻe toki hoko mai ʻae ikuʻanga.",
    latitude: -21,
    longitude: -175,
    direction: "ltr",
  },
  {
    id: "ukr1871",
    language: "Українська",
    languageInEnglish: "Ukrainian",
    text: "І проповідувати меть ся євангелия царства по всїй вселеннїй на сьвідкуваннє всїм народам; і тодї прийде конець.",
    latitude: 49,
    longitude: 32,
    direction: "ltr",
  },
  {
    id: "ulk1902",
    language: "Meriam Mir",
    languageInEnglish: "Meriam",
    text: "A ko etomeret debe baselaia ra mer gaire ged narid, ko ikeli ageakarem gaire ged narid; iaueakai bakedilu abele mop ge tabarki.",
    latitude: -10,
    longitude: 143,
    direction: "ltr",
  },
  {
    id: "vie1934",
    language: "Tiếng Việt",
    languageInEnglish: "Vietnamese",
    text: "Tin Lành nầy về nước Đức Chúa Trời sẽ được giảng ra khắp đất, để làm chứng cho muôn dân. Bấy giờ sự cuối cùng sẽ đến.",
    latitude: 16,
    longitude: 108,
    direction: "ltr",
  },
] as const
