-- Add compact provenance for scene vectors generated by Mastra and stored by
-- Admin. Nullable columns preserve existing scene embedding rows written before
-- the workflow migration.

ALTER TABLE "video_scene_locale"
  ADD COLUMN "source_artifact_key" text,
  ADD COLUMN "source_artifact_version" text,
  ADD COLUMN "source_content_hash" text,
  ADD COLUMN "source_provider" text,
  ADD COLUMN "source_generated_at" timestamp(3),
  ADD COLUMN "generation_mode" text,
  ADD COLUMN "mastra_run_id" text,
  ADD COLUMN "generated_at" timestamp(3);

CREATE INDEX "video_scene_locale_source_content_hash_idx"
  ON "video_scene_locale"("source_content_hash");

CREATE INDEX "video_scene_locale_mastra_run_id_idx"
  ON "video_scene_locale"("mastra_run_id");
