create schema if not exists devotional_workspace;
create extension if not exists vector;

create table if not exists devotional_workspace.schema_migrations (
  version integer primary key check (version > 0),
  name text not null,
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  applied_at timestamptz not null default now()
);

create table if not exists devotional_workspace.filesystem_mutation_audit (
  sequence_id bigint generated always as identity primary key,
  id text not null unique,
  occurred_at timestamptz not null,
  actor_id text not null,
  request_id text not null,
  action text not null check (
    action in ('write', 'append', 'delete', 'copy', 'move', 'mkdir', 'rmdir')
  ),
  path text not null,
  target_path text,
  pre_digest text check (pre_digest is null or pre_digest ~ '^[0-9a-f]{64}$'),
  post_digest text check (post_digest is null or post_digest ~ '^[0-9a-f]{64}$'),
  trusted_editorial_rights_assertion boolean not null default false
);

create index if not exists filesystem_mutation_audit_path_time_idx
  on devotional_workspace.filesystem_mutation_audit (path, occurred_at desc);

create or replace function devotional_workspace.reject_audit_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'filesystem mutation audit is append-only';
end;
$$;

drop trigger if exists filesystem_mutation_audit_append_only
  on devotional_workspace.filesystem_mutation_audit;
create trigger filesystem_mutation_audit_append_only
before update or delete on devotional_workspace.filesystem_mutation_audit
for each statement execute function devotional_workspace.reject_audit_mutation();

create table if not exists devotional_workspace.workspace_readiness (
  singleton boolean primary key default true check (singleton),
  ready boolean not null default false,
  manifest_digest text,
  reason text,
  verified_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into devotional_workspace.workspace_readiness (singleton, ready)
values (true, false)
on conflict (singleton) do nothing;

create table if not exists devotional_workspace.catalog_generations (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('staging', 'committed', 'failed', 'retired')),
  inventory_digest text not null,
  file_count integer not null check (file_count >= 0),
  decoded_bytes bigint not null check (decoded_bytes >= 0),
  vector_index_name text not null unique,
  failure_reason text,
  created_at timestamptz not null default now(),
  committed_at timestamptz,
  retired_at timestamptz
);

create table if not exists devotional_workspace.catalog_entries (
  generation_id bigint not null references devotional_workspace.catalog_generations(id) on delete cascade,
  path text not null,
  category text not null,
  digest text not null check (digest ~ '^[0-9a-f]{64}$'),
  byte_size integer not null check (byte_size >= 0),
  modified_at timestamptz,
  etag text,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  primary key (generation_id, path)
);

create index if not exists catalog_entries_category_idx
  on devotional_workspace.catalog_entries (generation_id, category, path);

create table if not exists devotional_workspace.catalog_head (
  singleton boolean primary key default true check (singleton),
  generation_id bigint not null references devotional_workspace.catalog_generations(id),
  updated_at timestamptz not null default now()
);

create table if not exists devotional_workspace.reconciliation_lease (
  singleton boolean primary key default true check (singleton),
  holder_id text not null,
  fencing_token bigint not null check (fencing_token > 0),
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create table if not exists devotional_workspace.workflow_attempts (
  id text primary key,
  parent_run_id text not null,
  idempotency_key text not null,
  request_hash text not null check (request_hash ~ '^[0-9a-f]{64}$'),
  attempt_number integer not null check (attempt_number > 0),
  catalog_generation bigint references devotional_workspace.catalog_generations(id),
  run_id text,
  selected_sources jsonb not null default '[]'::jsonb
    check (jsonb_typeof(selected_sources) = 'array'),
  provisioning_state text not null check (
    provisioning_state in ('provisioning', 'ready', 'failed')
  ),
  failure_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (parent_run_id, idempotency_key),
  unique (parent_run_id, attempt_number)
);

create table if not exists devotional_workspace.clip_state (
  chapter_id text primary key,
  use_count integer not null default 0 check (use_count >= 0),
  last_used_at timestamptz,
  reservation_id text unique,
  reservation_attempt_id text references devotional_workspace.workflow_attempts(id),
  pending_until timestamptz,
  publication_id text,
  updated_at timestamptz not null default now()
);

create table if not exists devotional_workspace.publication_intents (
  id text primary key,
  attempt_id text not null unique references devotional_workspace.workflow_attempts(id),
  request_hash text not null check (request_hash ~ '^[0-9a-f]{64}$'),
  receiver_idempotency_key text not null unique,
  state text not null check (state in ('pending', 'accepted', 'failed', 'ambiguous')),
  receiver_reference text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists devotional_workspace.publication_history (
  id text primary key,
  publication_intent_id text not null unique references devotional_workspace.publication_intents(id),
  chapter_id text not null,
  receiver_reference text not null,
  published_at timestamptz not null,
  created_at timestamptz not null default now()
);
