#!/usr/bin/env node
import { execFileSync } from "child_process"
import { writeFileSync } from "fs"
import path from "path"
import { fileURLToPath } from "url"

type Project = "cms" | "web"

type ProjectConfig = {
  outputFile: string
  defaultPaths: string[]
}

type SsmParameter = {
  Name: string
  Value?: string
}

type SsmGetParametersByPathResponse = {
  Parameters?: SsmParameter[]
  NextToken?: string
}

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
)

const PROJECT_CONFIG: Record<Project, ProjectConfig> = {
  cms: {
    outputFile: "apps/cms/.env.development.local",
    defaultPaths: ["/forge/aws/cms/stage/"],
  },
  web: {
    outputFile: "apps/web/.env.development.local",
    defaultPaths: [],
  },
}

function parseProjectArg(): Project {
  const idx = process.argv.indexOf("--project")
  const project = idx >= 0 ? process.argv[idx + 1] : "cms"
  if (project !== "cms" && project !== "web") {
    throw new Error("Invalid --project. Use one of: cms, web")
  }
  return project
}

function getPaths(project: Project): string[] {
  const projectEnvName = `SSM_SYNC_PATHS_${project.toUpperCase()}`
  const raw = process.env[projectEnvName] ?? process.env.SSM_SYNC_PATHS
  const defaults = PROJECT_CONFIG[project].defaultPaths
  if (!raw) return defaults
  return raw
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => (item.endsWith("/") ? item : `${item}/`))
}

function awsCli(args: string[]): SsmGetParametersByPathResponse {
  const out = execFileSync("aws", args, { encoding: "utf8" })
  return JSON.parse(out) as SsmGetParametersByPathResponse
}

function fetchAllByPath(ssmPath: string): SsmParameter[] {
  const parameters: SsmParameter[] = []
  let nextToken: string | undefined

  do {
    const args = [
      "ssm",
      "get-parameters-by-path",
      "--path",
      ssmPath,
      "--recursive",
      "--with-decryption",
      "--max-results",
      "10",
      "--output",
      "json",
    ]
    if (nextToken) args.push("--next-token", nextToken)
    const data = awsCli(args)
    parameters.push(...(data.Parameters ?? []))
    nextToken = data.NextToken
  } while (nextToken)

  return parameters
}

function toEnvKey(parameterName: string): string {
  const base = parameterName.split("/").filter(Boolean).pop() ?? parameterName
  return base.replace(/[^A-Za-z0-9_]/g, "_").toUpperCase()
}

function quoteEnvValue(value: string | undefined): string {
  return JSON.stringify(value ?? "")
}

function main(): void {
  const project = parseProjectArg()
  const outputFile = path.join(REPO_ROOT, PROJECT_CONFIG[project].outputFile)
  const paths = getPaths(project)
  if (paths.length === 0) {
    throw new Error(
      `No SSM paths configured for project '${project}'. Set SSM_SYNC_PATHS_${project.toUpperCase()} or SSM_SYNC_PATHS.`,
    )
  }
  const map = new Map<string, string>()

  for (const ssmPath of paths) {
    const parameters = fetchAllByPath(ssmPath)
    for (const parameter of parameters) {
      const envKey = toEnvKey(parameter.Name)
      map.set(envKey, parameter.Value ?? "")
    }
  }

  const keys = [...map.keys()].sort()
  const lines = [
    "# Generated by scripts/fetch-secrets.ts",
    `# Project: ${project}`,
    `# Source paths: ${paths.join(", ")}`,
    "",
    ...keys.map((key) => `${key}=${quoteEnvValue(map.get(key))}`),
    "",
  ]

  writeFileSync(outputFile, lines.join("\n"), "utf8")
  process.stdout.write(
    `Wrote ${keys.length} variables to ${PROJECT_CONFIG[project].outputFile}\n`,
  )
}

try {
  main()
} catch (error: unknown) {
  const message = error instanceof Error ? error.message : String(error)
  process.stderr.write(
    [
      "Failed to fetch secrets for dev.",
      "Ensure AWS CLI is installed and credentials can read SSM + decrypt KMS.",
      `Error: ${message}`,
      "",
    ].join("\n"),
  )
  process.exit(1)
}
