#!/usr/bin/env node
import { execFileSync } from "child_process"
import { writeFileSync } from "fs"
import path from "path"

type Project = "web"

type ProjectConfig = {
  defaultPath: string
  envFile: string
}

type SsmParameter = {
  Name: string
  Value?: string
}

type SsmGetParametersByPathResponse = {
  Parameters?: SsmParameter[]
  NextToken?: string
}

const AWS_PROFILE = "forge-dev-secrets"

const PROJECT_CONFIG: Record<Project, ProjectConfig> = {
  web: {
    defaultPath: "/forge/aws/web/dev/",
    envFile: ".env.development.local",
  },
}

function parseProjectArg(): Project {
  const idx = process.argv.indexOf("--project")
  const project = idx >= 0 ? process.argv[idx + 1] : "web"
  if (project === "cms") {
    throw new Error(
      "CMS secrets are no longer fetched from AWS SSM. Use Railway service variables instead.",
    )
  }
  if (project !== "web") {
    throw new Error("Invalid --project. Use: web")
  }
  return project
}

function awsCli(args: string[]): SsmGetParametersByPathResponse {
  const out = execFileSync("aws", args, { encoding: "utf8" })
  return JSON.parse(out) as SsmGetParametersByPathResponse
}

function fetchAllByPath(ssmPath: string): SsmParameter[] {
  const parameters: SsmParameter[] = []
  let nextToken: string | undefined

  do {
    const args = [
      "--profile",
      AWS_PROFILE,
      "ssm",
      "get-parameters-by-path",
      "--path",
      ssmPath,
      "--recursive",
      "--with-decryption",
      "--max-results",
      "10",
      "--output",
      "json",
    ]
    if (nextToken) args.push("--next-token", nextToken)
    const data = awsCli(args)
    parameters.push(...(data.Parameters ?? []))
    nextToken = data.NextToken
  } while (nextToken)

  return parameters
}

function toEnvKey(parameterName: string): string {
  const base = parameterName.split("/").filter(Boolean).pop() ?? parameterName
  return base.replace(/[^A-Za-z0-9_]/g, "_").toUpperCase()
}

function quoteEnvValue(value: string | undefined): string {
  return JSON.stringify(value ?? "")
}

function main(): void {
  const project = parseProjectArg()
  const { envFile } = PROJECT_CONFIG[project]
  const outputFile = path.resolve(process.cwd(), envFile)
  const sourcePath = PROJECT_CONFIG[project].defaultPath
  const map = new Map<string, string>()
  const keySources = new Map<string, string>()

  const parameters = fetchAllByPath(sourcePath)
  if (parameters.length === 0) {
    throw new Error(
      `No parameters found under '${sourcePath}' for project '${project}'`,
    )
  }
  for (const parameter of parameters) {
    const envKey = toEnvKey(parameter.Name)
    const previous = keySources.get(envKey)
    if (previous && previous !== parameter.Name) {
      throw new Error(
        `Duplicate env key '${envKey}' from '${previous}' and '${parameter.Name}'`,
      )
    }
    keySources.set(envKey, parameter.Name)
    map.set(envKey, parameter.Value ?? "")
  }

  const keys = [...map.keys()].sort()
  const lines = [
    "# Generated by scripts/fetch-secrets.ts",
    `# Project: ${project}`,
    "",
    ...keys.map((key) => `${key}=${quoteEnvValue(map.get(key))}`),
    "",
  ]

  writeFileSync(outputFile, lines.join("\n"), "utf8")
  process.stdout.write(`Wrote ${keys.length} variables to ${outputFile}\n`)
}

try {
  main()
} catch (error: unknown) {
  const message = error instanceof Error ? error.message : String(error)
  process.stderr.write(
    [
      "Failed to fetch secrets for dev.",
      "Ensure AWS CLI is installed and credentials can read SSM + decrypt KMS.",
      `Error: ${message}`,
      "",
    ].join("\n"),
  )
  process.exit(1)
}
