#!/usr/bin/env node
import { execFileSync } from "child_process"
import { writeFileSync } from "fs"
import path from "path"
import { fileURLToPath } from "url"

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
)
const OUTPUT_FILE = path.join(REPO_ROOT, ".env.development.local")
const DEFAULT_PATHS = ["/forge/aws/cms/stage/"]

function getPaths() {
  const raw = process.env.SSM_SYNC_PATHS
  if (!raw) return DEFAULT_PATHS
  return raw
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => (item.endsWith("/") ? item : `${item}/`))
}

function awsCli(args) {
  const out = execFileSync("aws", args, { encoding: "utf8" })
  return JSON.parse(out)
}

function fetchAllByPath(ssmPath) {
  const parameters = []
  let nextToken

  do {
    const args = [
      "ssm",
      "get-parameters-by-path",
      "--path",
      ssmPath,
      "--recursive",
      "--with-decryption",
      "--max-results",
      "10",
      "--output",
      "json",
    ]
    if (nextToken) args.push("--next-token", nextToken)
    const data = awsCli(args)
    parameters.push(...(data.Parameters ?? []))
    nextToken = data.NextToken
  } while (nextToken)

  return parameters
}

function toEnvKey(parameterName) {
  const base = parameterName.split("/").filter(Boolean).pop() ?? parameterName
  return base.replace(/[^A-Za-z0-9_]/g, "_").toUpperCase()
}

function quoteEnvValue(value) {
  return JSON.stringify(value ?? "")
}

function main() {
  const paths = getPaths()
  const map = new Map()

  for (const ssmPath of paths) {
    const parameters = fetchAllByPath(ssmPath)
    for (const parameter of parameters) {
      const envKey = toEnvKey(parameter.Name)
      map.set(envKey, parameter.Value ?? "")
    }
  }

  const keys = [...map.keys()].sort()
  const lines = [
    "# Generated by scripts/sync-ssm-dev.mjs",
    `# Source paths: ${paths.join(", ")}`,
    "",
    ...keys.map((key) => `${key}=${quoteEnvValue(map.get(key))}`),
    "",
  ]

  writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf8")
  process.stdout.write(
    `Wrote ${keys.length} variables to ${path.basename(OUTPUT_FILE)}\n`,
  )
}

try {
  main()
} catch (error) {
  process.stderr.write(
    [
      "Failed to sync SSM params for dev.",
      "Ensure AWS CLI is installed and credentials can read SSM + decrypt KMS.",
      `Error: ${error.message}`,
      "",
    ].join("\n"),
  )
  process.exit(1)
}
