#!/usr/bin/env node
import { execFileSync } from "child_process"
import { writeFileSync } from "fs"
import path from "path"
import { fileURLToPath } from "url"

const REPO_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
)

const PROJECT_CONFIG = {
  cms: {
    outputFile: "apps/cms/.env.development.local",
    defaultPaths: ["/forge/aws/cms/stage/"],
  },
  web: {
    outputFile: "apps/web/.env.development.local",
    defaultPaths: [],
  },
}

function parseProjectArg() {
  const idx = process.argv.indexOf("--project")
  const project = idx >= 0 ? process.argv[idx + 1] : "cms"
  if (!project || !(project in PROJECT_CONFIG)) {
    throw new Error("Invalid --project. Use one of: cms, web")
  }
  return project
}

function getPaths(project) {
  const projectEnvName = `SSM_SYNC_PATHS_${project.toUpperCase()}`
  const raw = process.env[projectEnvName] ?? process.env.SSM_SYNC_PATHS
  const defaults = PROJECT_CONFIG[project].defaultPaths
  if (!raw) return defaults
  return raw
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean)
    .map((item) => (item.endsWith("/") ? item : `${item}/`))
}

function awsCli(args) {
  const out = execFileSync("aws", args, { encoding: "utf8" })
  return JSON.parse(out)
}

function fetchAllByPath(ssmPath) {
  const parameters = []
  let nextToken

  do {
    const args = [
      "ssm",
      "get-parameters-by-path",
      "--path",
      ssmPath,
      "--recursive",
      "--with-decryption",
      "--max-results",
      "10",
      "--output",
      "json",
    ]
    if (nextToken) args.push("--next-token", nextToken)
    const data = awsCli(args)
    parameters.push(...(data.Parameters ?? []))
    nextToken = data.NextToken
  } while (nextToken)

  return parameters
}

function toEnvKey(parameterName) {
  const base = parameterName.split("/").filter(Boolean).pop() ?? parameterName
  return base.replace(/[^A-Za-z0-9_]/g, "_").toUpperCase()
}

function quoteEnvValue(value) {
  return JSON.stringify(value ?? "")
}

function main() {
  const project = parseProjectArg()
  const outputFile = path.join(REPO_ROOT, PROJECT_CONFIG[project].outputFile)
  const paths = getPaths(project)
  if (paths.length === 0) {
    throw new Error(
      `No SSM paths configured for project '${project}'. Set SSM_SYNC_PATHS_${project.toUpperCase()} or SSM_SYNC_PATHS.`,
    )
  }
  const map = new Map()

  for (const ssmPath of paths) {
    const parameters = fetchAllByPath(ssmPath)
    for (const parameter of parameters) {
      const envKey = toEnvKey(parameter.Name)
      map.set(envKey, parameter.Value ?? "")
    }
  }

  const keys = [...map.keys()].sort()
  const lines = [
    "# Generated by scripts/sync-ssm-dev.mjs",
    `# Project: ${project}`,
    `# Source paths: ${paths.join(", ")}`,
    "",
    ...keys.map((key) => `${key}=${quoteEnvValue(map.get(key))}`),
    "",
  ]

  writeFileSync(outputFile, lines.join("\n"), "utf8")
  process.stdout.write(
    `Wrote ${keys.length} variables to ${PROJECT_CONFIG[project].outputFile}\n`,
  )
}

try {
  main()
} catch (error) {
  process.stderr.write(
    [
      "Failed to sync SSM params for dev.",
      "Ensure AWS CLI is installed and credentials can read SSM + decrypt KMS.",
      `Error: ${error.message}`,
      "",
    ].join("\n"),
  )
  process.exit(1)
}
