// This file is generated by `pnpm --filter @forge/web generate:ui-locales`.
// Do not edit it by hand; add or remove apps/web/messages/*.json instead.

export const DEFAULT_LOCALE = "en" as const

export const AVAILABLE_UI_LOCALES = [
  "ar",
  "de",
  "en",
  "es",
  "fr",
  "id",
  "ja",
  "ko",
  "ms",
  "ne",
  "pt",
  "ru",
  "th",
  "tl",
  "tr",
  "vi",
  "zh",
  "zh-Hans",
  "zh-Hant",
] as const

export type UiLocale = (typeof AVAILABLE_UI_LOCALES)[number]

const AVAILABLE_UI_LOCALE_SET: ReadonlySet<string> = new Set(
  AVAILABLE_UI_LOCALES,
)

export function hasUiLocale(candidate: string): candidate is UiLocale {
  return AVAILABLE_UI_LOCALE_SET.has(candidate)
}
