query GetWatchExperience(
  $locale: I18NLocaleCode!
  $filters: ExperienceFiltersInput!
) {
  experiences(filters: $filters, locale: $locale) {
    documentId
    slug
    publishedAt
    blocks {
      ... on ComponentSectionsMediaCollection {
        ...MediaCollectionFields
      }
      ... on ComponentSectionsCta {
        ...CtaFields
      }
      ... on ComponentSectionsVideoHero {
        ...VideoHeroFields
      }
      ... on ComponentSectionsText {
        ...TextFields
      }
      ... on ComponentSectionsRelatedQuestions {
        ...RelatedQuestionsFields
      }
      ... on ComponentSectionsBibleQuotesCarousel {
        ...BibleQuotesCarouselFields
      }
      ... on ComponentSectionsCard {
        ...CardFields
      }
      ... on ComponentSectionsVideo {
        ...VideoSectionFields
      }
      ... on ComponentSectionsPromoBanner {
        id
      }
      ... on ComponentSectionsInfoBlocks {
        id
      }
      ... on ComponentSectionsContainer {
        id
        sectionKey
        slots {
          id
          gridSpan
          slotContent: content {
            ... on ComponentSectionsMediaCollection {
              ...MediaCollectionFields
            }
            ... on ComponentSectionsCta {
              ...CtaFields
            }
            ... on ComponentSectionsText {
              ...TextFields
            }
            ... on ComponentSectionsRelatedQuestions {
              ...RelatedQuestionsFields
            }
            ... on ComponentSectionsBibleQuotesCarousel {
              ...BibleQuotesCarouselFields
            }
            ... on ComponentSectionsCard {
              ...CardFields
            }
            ... on ComponentSectionsVideo {
              ...VideoSectionFields
            }
          }
        }
      }
      ... on ComponentSectionsSection {
        id
        sectionKey
        backgroundColor
        blurHash
        sectionContent: content {
          ... on ComponentSectionsMediaCollection {
            ...MediaCollectionFields
          }
          ... on ComponentSectionsCta {
            ...CtaFields
          }
          ... on ComponentSectionsText {
            ...TextFields
          }
          ... on ComponentSectionsRelatedQuestions {
            ...RelatedQuestionsFields
          }
          ... on ComponentSectionsBibleQuotesCarousel {
            ...BibleQuotesCarouselFields
          }
          ... on ComponentSectionsCard {
            ...CardFields
          }
          ... on ComponentSectionsVideo {
            ...VideoSectionFields
          }
          ... on ComponentSectionsPromoBanner {
            id
          }
          ... on ComponentSectionsInfoBlocks {
            id
          }
          ... on ComponentSectionsContainer {
            id
            sectionKey
            slots {
              id
              gridSpan
              slotContent: content {
                ... on ComponentSectionsMediaCollection {
                  ...MediaCollectionFields
                }
                ... on ComponentSectionsCta {
                  ...CtaFields
                }
                ... on ComponentSectionsText {
                  ...TextFields
                }
                ... on ComponentSectionsRelatedQuestions {
                  ...RelatedQuestionsFields
                }
                ... on ComponentSectionsBibleQuotesCarousel {
                  ...BibleQuotesCarouselFields
                }
                ... on ComponentSectionsCard {
                  ...CardFields
                }
                ... on ComponentSectionsVideo {
                  ...VideoSectionFields
                }
              }
            }
          }
        }
      }
    }
  }
}
