#!/usr/bin/env tsx
/**
 * Emit admin's Pothos schema as a deterministic SDL artifact.
 *
 * Mirrors Strapi's pattern (`apps/cms/schema.graphql` is committed and
 * regenerated by Strapi's GraphQL plugin lifecycle). For admin, this
 * script is the source of truth for keeping the committed SDL in sync
 * with the live Pothos schema. The committed SDL is what
 * `packages/graphql`'s gql.tada codegen reads to produce the typed
 * `adminGraphql()` factory and its introspection types — consumer apps
 * never introspect admin's running server.
 *
 * Determinism comes from `lexicographicSortSchema` (sorts types and
 * fields alphabetically). Without it, `printSchema` would emit types in
 * registration order, producing spurious diffs between runs even when
 * nothing changed.
 *
 * Pothos directives (e.g., `@authScopes` from scope-auth) are stripped
 * post-print: gql.tada's parser does not tolerate non-standard SDL
 * directive declarations, and downstream consumers never need them
 * (auth is enforced at the resolver, not declared via directive in the
 * SDL).
 *
 * Usage:
 *   pnpm --filter @forge/admin schema:print
 *
 * Writes apps/admin/schema.graphql with a "do not edit" header.
 *
 * Drift detection lives in `.github/workflows/ci.yml`'s
 * `admin-schema-drift` job, which runs this script in CI and fails the
 * build if the committed artifact has drifted from the live schema.
 */

import { writeFileSync } from "node:fs"
import { resolve } from "node:path"
import { lexicographicSortSchema, printSchema } from "graphql"

import { schema } from "@/graphql/schema"

const HEADER = `# This file is generated by apps/admin/src/scripts/print-schema.ts
# DO NOT EDIT THIS FILE DIRECTLY — your changes will be overwritten.
#
# Regenerate with:
#   pnpm --filter @forge/admin schema:print
#
# The committed SDL is consumed by packages/graphql's gql.tada codegen
# to produce the typed adminGraphql() factory + introspection types.
# Consumer apps (web, mobile, tv) never introspect admin's running
# server — admin disables introspection in production via
# @envelop/disable-introspection.

`

/**
 * Strip Pothos plugin directives from the printed SDL.
 *
 * `lexicographicSortSchema(builder.toSchema())` emits scope-auth's
 * `@authScopes` directive and any directive declaration the schema
 * carries. gql.tada's tsconfig-side parser (used during consumer
 * codegen) accepts standard GraphQL directives but errors on
 * non-introspectable directive *declarations* of unknown shape. We
 * strip both the directive declarations (top of the file) and any
 * `@authScopes(...)` usages on type/field definitions.
 *
 * Other plugin directives that may appear in the future (e.g., from
 * `@pothos/plugin-validation` or `@pothos/plugin-tracing`) follow the
 * same shape — extend the regex set as new plugins land.
 */
function stripPothosDirectives(sdl: string): string {
  return (
    sdl
      // Drop directive declarations (e.g. `directive @authScopes ...`).
      .replace(/^directive @\w+[^\n]*(\non[^\n]*)?\n/gm, "")
      // Drop `@authScopes(...)` directive usages on fields/types.
      .replace(/ @authScopes\([^)]*\)/g, "")
      // Collapse runs of blank lines created by removed declarations.
      .replace(/\n{3,}/g, "\n\n")
  )
}

function main(): void {
  const sortedSchema = lexicographicSortSchema(schema)
  const rawSdl = printSchema(sortedSchema)
  const cleanedSdl = stripPothosDirectives(rawSdl)

  // Resolve relative to admin's package root (cwd when invoked via
  // `pnpm --filter @forge/admin schema:print`).
  const outputPath = resolve(process.cwd(), "schema.graphql")
  writeFileSync(outputPath, HEADER + cleanedSdl + "\n", "utf8")

  process.stdout.write(
    `[schema:print] wrote ${cleanedSdl.length} chars to ${outputPath}\n`,
  )
}

main()
