#!/usr/bin/env tsx
/**
 * Emit admin's Pothos schema as a deterministic SDL artifact.
 *
 * This script is the source of truth for keeping the committed SDL in
 * sync with the live Pothos schema. The committed SDL is what
 * `packages/admin-graphql`'s gql.tada codegen reads to produce the typed
 * `adminGraphql()` factory and its introspection types — consumer apps
 * never introspect admin's running server.
 *
 * Determinism comes from `lexicographicSortSchema` (sorts types and
 * fields alphabetically). Without it, `printSchema` would emit types in
 * registration order, producing spurious diffs between runs even when
 * nothing changed.
 *
 * Pothos directives (e.g., `@authScopes` from scope-auth) are stripped
 * post-print: gql.tada's parser does not tolerate non-standard SDL
 * directive declarations, and downstream consumers never need them
 * (auth is enforced at the resolver, not declared via directive in the
 * SDL).
 *
 * Usage:
 *   pnpm --filter @forge/admin schema:print
 *
 * Writes apps/admin/schema.graphql with a "do not edit" header.
 *
 * Drift detection lives in `.github/workflows/ci.yml`'s
 * `admin-schema-drift` job, which runs this script in CI and fails the
 * build if the committed artifact has drifted from the live schema.
 */

import { writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import {
  lexicographicSortSchema,
  parse,
  print,
  printSchema,
  visit,
} from "graphql"

// Anchor the output path to this script's location, NOT process.cwd().
// pnpm/Turbo invocation sets cwd correctly; raw `tsx apps/admin/src/scripts/
// print-schema.ts` from the repo root would otherwise write schema.graphql
// to the wrong place and silently false-pass the drift CI check.
const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url))
const ADMIN_PKG_ROOT = resolve(SCRIPT_DIR, "../..")

const HEADER = `# This file is generated by apps/admin/src/scripts/print-schema.ts
# DO NOT EDIT THIS FILE DIRECTLY — your changes will be overwritten.
#
# Regenerate with:
#   pnpm --filter @forge/admin schema:print
#
# The committed SDL is consumed by packages/admin-graphql's gql.tada codegen
# to produce the typed adminGraphql() factory + introspection types.
# Consumer apps (web, mobile, tv) never introspect admin's running
# server — admin disables introspection in production via
# @envelop/disable-introspection.

`

/**
 * Names of Pothos plugin directives we strip from the emitted SDL.
 *
 * gql.tada's tsconfig-side parser accepts standard GraphQL directives but
 * errors on non-introspectable directive declarations of unknown shape.
 * Auth is enforced at the resolver, not declared via the SDL surface
 * consumers see, so stripping these is safe.
 *
 * Add new entries when new Pothos plugins land that emit directive
 * declarations (e.g., `@pothos/plugin-validation`, `@pothos/plugin-tracing`).
 */
const POTHOS_DIRECTIVE_NAMES = new Set(["authScopes"])

/**
 * Strip Pothos plugin directives from the printed SDL via AST round-trip.
 *
 * Why AST instead of regex: a regex stripper can mismatch in three concrete
 * ways — (a) `@authScopes(...)` substrings inside field DESCRIPTIONS get
 * erased, silently corrupting documentation; (b) directive declarations
 * spanning multiple lines (long `on` clauses) leak into the output;
 * (c) directive args containing nested parens or quote-escaped parens
 * confuse the `[^)]*` heuristic. The AST approach is structurally aware:
 * it removes nodes by their `kind` and `name`, regardless of formatting,
 * argument shape, or surrounding text.
 *
 * The round-trip is `parse(printSchema(...))` then `print(visit(...))`.
 * graphql-js's `print` produces canonical formatting that's deterministic
 * across runs (same input → byte-identical output).
 */
function stripPothosDirectives(sdl: string): string {
  const document = parse(sdl)

  // Drop both directive DEFINITIONS (top-of-file `directive @authScopes ...`)
  // and directive USAGES (`@authScopes(...)` on fields/types) in a single
  // visit. `visit` walks every node; returning `null` removes it.
  const cleaned = visit(document, {
    DirectiveDefinition(node) {
      return POTHOS_DIRECTIVE_NAMES.has(node.name.value) ? null : undefined
    },
    Directive(node) {
      return POTHOS_DIRECTIVE_NAMES.has(node.name.value) ? null : undefined
    },
  })

  return print(cleaned)
}

async function main(): Promise<void> {
  process.env.CI ??= "1"
  process.env.DATABASE_URL ??=
    "postgresql://forge:forge@localhost:5432/forge_admin"
  process.env.ADMIN_SESSION_SECRET ??=
    "forge-admin-schema-print-secret-min-32-chars"
  process.env.AUTH_ISSUER_URL ??= "http://localhost:3004"
  process.env.AUTH_ADMIN_CLIENT_ID ??= "admin-schema-print"

  const { schema } = await import("@/graphql/schema")
  const sortedSchema = lexicographicSortSchema(schema)
  const rawSdl = printSchema(sortedSchema)
  const cleanedSdl = stripPothosDirectives(rawSdl)

  // Resolve relative to admin's package root, derived from this script's own
  // location. cwd-based resolution would silently land in the wrong directory
  // when invoked via raw `tsx` from the repo root.
  const outputPath = resolve(ADMIN_PKG_ROOT, "schema.graphql")

  try {
    writeFileSync(outputPath, HEADER + cleanedSdl + "\n", "utf8")
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err)
    process.stderr.write(
      `[schema:print] failed to write ${outputPath}: ${reason}\n`,
    )
    process.exit(1)
  }

  process.stdout.write(
    `[schema:print] wrote ${cleanedSdl.length} chars to ${outputPath}\n`,
  )
}

void main()
