import { readFileSync } from "node:fs"

import { describe, expect, it, vi } from "vitest"

import { PUBLIC_WATCH_LANGUAGE_SLUGS } from "@forge/watch-url-policy/routes"

import { LANGUAGE_BCP47_MAP } from "./language-bcp47-map"
import {
  ADMIN_LANGUAGES_PAGE_SIZE,
  PRODUCTION_ADMIN_GRAPHQL_URL,
  PUBLIC_WATCH_LANGUAGE_SLUG_OVERRIDES,
  buildLanguageBcp47Map,
  parseGenerateLanguageBcp47MapArgs,
  buildPublicWatchLanguageSlugs,
  diffLanguageCorpus,
  fetchAdminLanguages,
  hasLanguageCorpusDrift,
  parseLanguageBcp47MapSource,
  parsePublicWatchLanguageSlugsSource,
  renderLanguageBcp47MapSource,
  renderPublicWatchLanguageSlugsSource,
} from "./language-bcp47-map-codegen"

describe("buildLanguageBcp47Map", () => {
  it("keeps well-formed rows, sorts by code point, and reports skips by reason", () => {
    const { map, skipped } = buildLanguageBcp47Map([
      { slug: "zulu", bcp47: "zu" },
      { slug: "a-hmao", bcp47: "hmd" },
      { slug: "aari", bcp47: "aiw" },
      { slug: null, bcp47: "leb" },
      { slug: "no-tag", bcp47: null },
      { slug: "Bad Slug", bcp47: "xx" },
      { slug: "bad-tag", bcp47: "not a tag" },
      // Admin's private-use subtags exceed RFC 5646's 8-char limit; keep them.
      { slug: "hamgyongdo", bcp47: "ko-x-Hamgyongdo" },
      { slug: "chinese-yunnan-kunming", bcp47: "zh-CN-53-x-Kunming" },
    ])

    expect(Object.keys(map)).toEqual([
      "a-hmao",
      "aari",
      "chinese-yunnan-kunming",
      "hamgyongdo",
      "zulu",
    ])
    expect(map.hamgyongdo).toBe("ko-x-Hamgyongdo")
    expect(skipped.map((entry) => entry.reason)).toEqual([
      "missing-slug",
      "missing-bcp47",
      "invalid-slug",
      "invalid-bcp47",
    ])
  })

  it("keeps a well-formed slug in the URL corpus even when its BCP-47 is missing or malformed", () => {
    // Admin's route manifest admits a playable language by slug alone, so the
    // URL corpus must not depend on the tag. (39 such rows existed at the
    // 2026-05-28 snapshot and were silently unroutable.)
    const { map, publicSlugs } = buildLanguageBcp47Map([
      { slug: "no-tag", bcp47: null },
      { slug: "bad-tag", bcp47: "not a tag" },
      { slug: "zulu", bcp47: "zu" },
    ])
    expect(publicSlugs).toEqual(["bad-tag", "no-tag", "zulu"])
    expect(Object.keys(map)).toEqual(["zulu"])
  })
})

describe("buildPublicWatchLanguageSlugs", () => {
  it("unions the upstream slugs with the public URL overrides, deduplicated and sorted", () => {
    expect(
      buildPublicWatchLanguageSlugs(
        ["zulu", "spanish-latin-american", "aari"],
        ["spanish-latin-american", "english-british"],
      ),
    ).toEqual(["aari", "english-british", "spanish-latin-american", "zulu"])
  })

  it("pins the override every HTML_LANG_OVERRIDES consumer relies on", () => {
    expect(PUBLIC_WATCH_LANGUAGE_SLUG_OVERRIDES).toEqual([
      "spanish-latin-american",
    ])
  })
})

describe("render + parse round trip", () => {
  const map = { "a-hmao": "hmd", aari: "aiw", "1-digit-first": "xx" }

  it("renders the BCP-47 map as Prettier-shaped TypeScript and parses it back", () => {
    const source = renderLanguageBcp47MapSource(map, {
      generatedOn: "2026-09-04",
      skippedCount: 1,
    })
    expect(source).toContain(
      "// AUTOGENERATED from admin Language.bcp47 on 2026-09-04",
    )
    expect(source).toContain("// 3 entries (1 admin rows skipped")
    expect(source).toContain('    "a-hmao": "hmd",')
    expect(source).toContain('    aari: "aiw",')
    expect(source).toContain('    "1-digit-first": "xx",')
    expect(parseLanguageBcp47MapSource(source)).toEqual(map)
  })

  it("renders the slug corpus and parses it back", () => {
    const slugs = ["a-hmao", "aari", "zulu"]
    const source = renderPublicWatchLanguageSlugsSource(slugs)
    expect(source).toContain(
      "export const PUBLIC_WATCH_LANGUAGE_SLUGS: ReadonlySet<string>",
    )
    expect(parsePublicWatchLanguageSlugsSource(source)).toEqual(slugs)
  })

  it("parses the committed generated files (the --check baseline)", () => {
    // The parser must read the real artifacts, or --check compares against
    // an empty baseline and reports every language as newly added.
    const mapSource = readFileSync(
      new URL("./language-bcp47-map.ts", import.meta.url),
      "utf8",
    )
    const corpusSource = readFileSync(
      new URL(
        "../../../../packages/watch-url-policy/src/public-watch-language-slugs.ts",
        import.meta.url,
      ),
      "utf8",
    )
    expect(parseLanguageBcp47MapSource(mapSource)).toEqual(LANGUAGE_BCP47_MAP)
    expect(new Set(parsePublicWatchLanguageSlugsSource(corpusSource))).toEqual(
      PUBLIC_WATCH_LANGUAGE_SLUGS,
    )
  })
})

describe("diffLanguageCorpus", () => {
  it("reports added, removed, and changed slugs sorted", () => {
    const diff = diffLanguageCorpus(
      { english: "en", spanish: "es", zulu: "zu" },
      { english: "en", "german-pennsylvania": "pdc", zulu: "zul" },
    )
    expect(diff).toEqual({
      added: ["german-pennsylvania"],
      removed: ["spanish"],
      changed: [{ slug: "zulu", from: "zu", to: "zul" }],
    })
    expect(hasLanguageCorpusDrift(diff)).toBe(true)
    expect(
      hasLanguageCorpusDrift(diffLanguageCorpus({ a: "a" }, { a: "a" })),
    ).toBe(false)
  })
})

describe("fetchAdminLanguages", () => {
  function jsonResponse(languages: unknown[]): Response {
    return new Response(JSON.stringify({ data: { languages } }), {
      status: 200,
      headers: { "content-type": "application/json" },
    })
  }

  it("pages at admin's 500-row cap until a short page and sends no bearer", async () => {
    const fetchImpl = vi
      .fn<typeof fetch>()
      .mockResolvedValueOnce(
        jsonResponse(
          Array.from({ length: ADMIN_LANGUAGES_PAGE_SIZE }, (_, index) => ({
            slug: `lang-${index}`,
            bcp47: "xx",
          })),
        ),
      )
      .mockResolvedValueOnce(jsonResponse([{ slug: "zulu", bcp47: "zu" }]))

    const rows = await fetchAdminLanguages({
      adminGraphqlUrl: "https://admin.example/api/graphql",
      fetchImpl,
    })

    expect(rows).toHaveLength(ADMIN_LANGUAGES_PAGE_SIZE + 1)
    expect(fetchImpl).toHaveBeenCalledTimes(2)
    const [, secondInit] = fetchImpl.mock.calls[1] ?? []
    expect(JSON.parse(String(secondInit?.body)).variables).toEqual({
      limit: ADMIN_LANGUAGES_PAGE_SIZE,
      offset: ADMIN_LANGUAGES_PAGE_SIZE,
    })
    expect(new Headers(secondInit?.headers).has("authorization")).toBe(false)
    // Every page carries a timeout so a hung admin fails the scheduled job
    // instead of stalling it until the runner's job timeout.
    expect(secondInit?.signal).toBeInstanceOf(AbortSignal)
  })

  it("rejects when a page exceeds the timeout budget", async () => {
    const fetchImpl: typeof fetch = (_url, init) =>
      new Promise((_resolve, reject) => {
        init?.signal?.addEventListener("abort", () =>
          reject(init.signal?.reason ?? new Error("aborted")),
        )
      })

    await expect(
      fetchAdminLanguages({
        adminGraphqlUrl: "https://admin.example/api/graphql",
        fetchImpl,
        timeoutMs: 20,
      }),
    ).rejects.toMatchObject({ name: "TimeoutError" })
  })

  it("throws on HTTP failures and GraphQL errors instead of writing a truncated corpus", async () => {
    await expect(
      fetchAdminLanguages({
        adminGraphqlUrl: "https://admin.example/api/graphql",
        fetchImpl: vi
          .fn<typeof fetch>()
          .mockResolvedValue(new Response("nope", { status: 503 })),
      }),
    ).rejects.toThrow("HTTP 503")

    await expect(
      fetchAdminLanguages({
        adminGraphqlUrl: "https://admin.example/api/graphql",
        fetchImpl: vi.fn<typeof fetch>().mockResolvedValue(
          new Response(JSON.stringify({ errors: [{ message: "denied" }] }), {
            status: 200,
          }),
        ),
      }),
    ).rejects.toThrow("denied")
  })
})

describe("parseGenerateLanguageBcp47MapArgs", () => {
  it("defaults to a generating run against production admin", () => {
    expect(parseGenerateLanguageBcp47MapArgs([])).toEqual({
      check: false,
      adminGraphqlUrl: PRODUCTION_ADMIN_GRAPHQL_URL,
    })
  })

  it("prefers --admin-url over the environment, and the environment over production", () => {
    const env = { ADMIN_GRAPHQL_URL: "http://localhost:1437/admin/api/graphql" }
    expect(parseGenerateLanguageBcp47MapArgs(["--check"], env)).toEqual({
      check: true,
      adminGraphqlUrl: "http://localhost:1437/admin/api/graphql",
    })
    expect(
      parseGenerateLanguageBcp47MapArgs(
        ["--admin-url", "https://admin.example/api/graphql", "--check"],
        env,
      ),
    ).toEqual({
      check: true,
      adminGraphqlUrl: "https://admin.example/api/graphql",
    })
  })

  it("fails fast on unknown flags and malformed URLs", () => {
    expect(() => parseGenerateLanguageBcp47MapArgs(["--nope"])).toThrow(
      "Unknown argument --nope",
    )
    expect(() =>
      parseGenerateLanguageBcp47MapArgs(["--admin-url", "not a url"]),
    ).toThrow()
  })
})
